### ISSUE TITLE
[feature] Supporting IndieWeb, Webmentions and microformats 

### ISSUE THREAD

**Issue by xplosionmind** [superseriousbusiness/gotosocial#1020]
### Is your feature request related to a problem ?

No

### Describe the solution you'd like.

It would be great if GTS could support:

- [ ] [The micropub standard](https://www.w3.org/TR/micropub)
- [ ] [Microformats](https://microformats.org)
- [ ] [IndieAuth](https://www.w3.org/TR/indieauth)
- [ ] [Webmentions](https://www.w3.org/TR/webmention)

### Describe alternatives you've considered.

None

**Comment by doenietzomoeilijk** [comment]
I think this could be two separate issues: adding microformats to the output (ezpz), and adding whatever functionality you envision when you talk about webmentions (requires a good think).

The microformats thing could theoretically be done in an afternoon — I might even take a crack at it, if nobody else is already working on it.

**Comment by tsmethurst** [comment]
Heya, I'm gonna close this as "won't implement" because out of the four things you mentioned, I think only Microformats (https://github.com/superseriousbusiness/gotosocial/issues/2959) is really relevant to GoToSocial at this point.

The other things (micropub, indieauth, and webmentions) are basically superseded for GtS by the functionality of ActivityPub+ActivityStreams, plus the Mastodon client API for connecting to the server itself. So in server-to-server terms, I think we can get by with just the AP protocol, and in client-to-server terms, the Mastodon client API is enough (for now, anyway). Adding support for the other specs/protocols would be extra work for little payoff at this point (and adds more code surface to maintain/debug).

We might wanna revisit this in future; if so we can reopen this issue :)
