### ISSUE TITLE
Feature request: Markdown support

### ISSUE THREAD

**Issue by jk-na** [superseriousbusiness/gotosocial#110]
A consideration for a bit further down the road perhaps?  I know that opinions a bit split in the fediverse with regards to the degree that users should be able to manipulate formatting but for my somewhat unique use case it would be great to have markdown input handled by the API.  

That use case being that I post to my site using markdown and then it is syndicates to GtS, even now with pleroma they only handle markdown at the front-end, not via the API so posts including markdown formatted links are somewhat ugly when they hit pleroma.

**Comment by tsmethurst** [comment]
Yep yep yep, I was already looking a while ago into how to support this because I also really want it.

Would probably do it using this library: https://github.com/gomarkdown/markdown

And then sanitizing the generated HTML through BlueMonday as we do with normal posts.

The only thing left to figure out then is how to signal to GtS that a post is being submitted in Markdown. We could try to determine it automatically, but I think that's going to get messy. Probably we can add a `format` field to submitted posts, with a default of `plain` but a possibility to set it to `markdown` to instruct GtS to parse it as an md document.
