### ISSUE TITLE
[proposal/enhancement] terminology: replace "instance" with "community" or similar

### ISSUE THREAD

**Issue by noerw** [superseriousbusiness/gotosocial#1103]
### Is your feature request related to a problem ?

People new to the fediverse are confused by the term 'instance'.

- https://mastodon.ie/@Ciaraioch/109287818715515862

- just look at any guide to the fediverse, which will almost certainly start with an explanation to the term 'instance'

### Describe the solution you'd like.

A term that worked well in my experience talking to prospective or new fedi users is to use the term 'community' / 'communities' instead.

Replace all instances (hah) of 'instance' with 'community' in the user facing parts of GtS (i.e. mostly the landing page, user facing docs, and error messages maybe)

GtS is probably not the most meaningful place to propose this change - but if it adapts, that's a neat data point in discussions elsewhere.

### Describe alternatives you've considered.

One could argue it's too late to change this established (with existing users) term, but discord also went from 'guild' to 'server' rather late and quickly.

'community' would become overloaded with meaning both people and infrastructure, so it has its own issues. Empirically (n~=10), it seems to communicate the concept much better though.

"Server" - although more technical - could be good too, as it got/gets popularized by discord (although there with a weird meaning that negates the decentralized nature of the fediverse).

### Additional context.

- old, stalled discussion on mastodon https://github.com/mastodon/mastodon/issues/8349
- somewhat related: ambiguity in the term `local timeline` https://github.com/mastodon/mastodon/issues/6812

**Comment by tsmethurst** [comment]
Heya, I think one issue with using the word 'community' instead of 'instance' is that it doesn't really work for single-user instances, which is one thing that GtS is particularly suitable for and will likely get used for a lot. Having a community of 1 doesn't really make sense.

I'm also not that keen on 'server', myself, because it's not really accurate: you run GtS on a server, but you don't really have a GtS server per se.

I think since there are already so many documents explaining what an 'instance' is, and that term is already embedded in our code + API, changing it to something else is likely to be more trouble than it's worth...

**Comment by noerw** [comment]
> Having a community of 1 doesn't really make sense.

that's a good point.

> I'm also not that keen on 'server'

agree, it's a marginal improvement at best

as i don't have other better suggestions I'm closing this :D
