### ISSUE TITLE
[bug] Out Of Memory Crash When Using S3 Backend.

### ISSUE THREAD

**Issue by ethanrjones97** [superseriousbusiness/gotosocial#1105]
### Describe the bug with a clear and concise description of what the bug is.

Hello, I've been attempting to run GoToSocial on fly.io for a bit now. 

My current blocker is the server seems to get OOM killed when using the S3 backend. This can be alleviated by increasing the amount of memory (256MB is the default, 1GB seems to prevent it from being killed immediately) however it does run out of memory within 12 or so hours. Image size does not appear to be related as a 55kB JPEG reproduced the crash multiple times.

### What's your GoToSocial Version?

0.5.1-SNAPSHOT git-81c1fe0

### GoToSocial Arch

x86_64 Docker

### Browser version

Firefox 106.0.4 on Fedora Linux

### What happened?

With 256MB - 512MB when uploading an image the application gets killed immediately with an OOM error. 

With 1GB+ RAM, after about 12 hours the application crashes with OOM error.

### What you expected to happen?

The application uploads the image to BackBlaze B2 and continues running. 

### How to reproduce it?

Use the S3 backend with B2 and upload an image. Use =<512MB RAM for immediate effects and >=1GB for a delayed crash.

### Anything else we need to know?

My stack is using fly.io with the following config. Secrets are exported via `fly secrets set...`
[fly.toml.txt](https://github.com/superseriousbusiness/gotosocial/files/10053285/fly.toml.txt)
And the crash log is as follows.
[gts-panic-b2-nov-20.txt](https://github.com/superseriousbusiness/gotosocial/files/10053297/gts-panic-b2-nov-20.txt)

**Comment by Follpvosten** [comment]
I have not noticed it as much, but I think I might be hitting this issue as well. I'm on a server with 8GB of RAM so it's not as much of a problem, but apparently it does happen at times.

![screenshot from my server's VNC console](https://user-images.githubusercontent.com/22855787/202984528-0808f873-6711-42ce-b585-6c3df65675db.png)

Right now looking at GtS in htop it was sitting at 266MB RES, but soon jumped up to 1.5GB and then later 2GB, without going down below 1.5 again. It sounds to me like either there's a circular reference issue somewhere, or the GC isn't getting active at all for some reason. I'm also curious as to what would use so much memory in the first place, because with 1GB RAM or less it probably just would've crashed.

I am also using S3 but can't say if that is or isn't related.

**Comment by theSuess** [comment]
Just to provide some data, this is the memory utilization of my instance - also using S3:

![image](https://user-images.githubusercontent.com/1364576/202999910-6c1997f6-e375-4237-930e-d77a56e65e23.png)

memory is getting freed again, but the spikes are indeed very weird

I *might* have an idea where these spikes might be originating. I'll check my suspicion after work today

**Comment by ruifung** [comment]
I just set up my instance and straight up ran into this.

In my case, I'm deploying it on a small GKS cluster, and simply *searching* for someone on another server is enough to have the memory usage spike to 1GB, followed by the node just outright dying because kubelet got OOM-killed.

**Comment by tsmethurst** [comment]
this should be closed by https://github.com/superseriousbusiness/gotosocial/pull/1113 which we'll include in a release shortly, so i'll close this issue -- feel free to open it again if the problems reoccurs though

**Comment by confraria** [comment]
this sorted it out wonderfully 🤩 thank you!

**Comment by NoraCodes** [comment]
I just wanted to chime in with just _how_ much of an improvement this has been, @tsmethurst. I installed 0.6.0 on pyrite  December 9, 20:11 (Chicago time), denoted by the blue line in this image, and you can see the immediate improvement in memory performance.

Thank you!

![gts_0 6 0_improvement](https://user-images.githubusercontent.com/3290365/207089612-9f89d93e-4e50-4fcb-9f3f-6a6f31b4c23c.png)
