### ISSUE TITLE
[bug] Version string on Snapshot wrong

### ISSUE THREAD

**Issue by ppetermann** [superseriousbusiness/gotosocial#1109]
### Describe the bug with a clear and concise description of what the bug is.

the current snapshot docker image states that it is:
`GoToSocial 0.5.1-SNAPSHOT git-4a95385`

the git hash is the current status of the main branch, so it is the current snapshot,
but the version string given is 0.5.1, where 0.5.2 was released at the beginning of this month,
so either this should be 0.5.2 or the next version being mentioned here? 

### What's your GoToSocial Version?

"GoToSocial 0.5.1-SNAPSHOT git-4a95385"

**Comment by tsmethurst** [comment]
Yeah, this has been bugging me too. I think it's a consequence of GoReleaser not handling deleted tags very well, and we deleted our release candidate tags when we were finished with them.

This should be resolved in the next release since it will say 0.6.0 properly, and then i'll avoid deleting the rc tags :)

**Comment by ppetermann** [comment]
given that this means that there is no change in code necessary to fix it, i've closed the ticket
