### ISSUE TITLE
[bug] Brutaldon cannot be connected to a GtS instance

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#113]
Currently Brutaldon (https://brutaldon.org/login) gives a 500 server error when trying to log into `gts.superseriousbusiness.org`. We should investigate why this is and make sure Brutaldon can connect to GtS.

**Comment by daenney** [comment]
This has been fixed in Brutaldon: https://gitlab.com/brutaldon/brutaldon/-/merge_requests/11 (the branch is named fix-gts :smile:). They updated their calls to the mastodon.py library to disable the version checking.

That commit went in 5 months ago but unfortunately they haven't tagged a new version. The last one is from 3 years ago. I've verified this works fine now if you use a Brutaldon built from main. At this point all we can do is wait for them to do a release. I think we can close this now.

**Comment by tsmethurst** [comment]
Alright, thanks for investigating :)
