### ISSUE TITLE
[feature] Account `move` activity for instance migration

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#130]
Mastodon allows an account to migrate from one instance to another, as documented here:

https://docs.joinmastodon.org/user/moving/#migration

Under the hood, this uses a combination of the activitypub `move` activity, and the `alsoKnownAs` field on profiles, as documented here:

https://docs.joinmastodon.org/spec/activitypub/#profile

It would be very cool if GoToSocial was able to support this as well, to allow accounts to move freely across instances with different AP implementations and features.

In order to do this, we need to first add `alsoKnownAs` to the library that GoToSocial uses for federation: https://github.com/go-fed/activity -- using astool: https://github.com/go-fed/activity/tree/master/astool. Then, either we make a PR against that repo (preferred), or we fork the repo and use our own fork (much less preferred, and silly).

Once that's done, we need to implement some functionality in GtS for setting `alsoKnownAs` -- probably through a PATCH to the `/api/v1/accounts/update_credentials` path (https://github.com/superseriousbusiness/gotosocial/blob/main/internal/api/client/account/accountupdate.go). This PATCH would update this field in the account model: https://github.com/superseriousbusiness/gotosocial/blob/main/internal/gtsmodel/account.go#L112

Finally, we'd need to implement the `move` activity in the federating database -- https://github.com/superseriousbusiness/gotosocial/tree/main/internal/federation/federatingdb -- and process side effects in the processor somewhere -- https://github.com/superseriousbusiness/gotosocial/blob/main/internal/processing/fromfederator.go

**Comment by GitpayPop** [comment]
This issue was added to Gitpay, check the task [https://gitpay.me/#/task/612](https://gitpay.me/#/task/612) 💝

[About Gitpay platform](https://gitpay.me).

For portuguese, you can [access the portuguese version](https://github.com/worknenjoy/gitpay-github-app/blob/master/first-comment.pt-br.md)

### 📋 Step by Step

#### If you are the task owner who created this issue
- [x] 🔔 ***Issue open*** an issue was created
- [x] 👌 **Issue added on Gitpay** this issue was added on gitpay [https://gitpay.me/#/task/612](https://gitpay.me/#/task/612)
- [ ] 📝 **Add bounties** A bounty is added to get things done
- [ ] 📝 **Set a deadline** A deadline to finish the task (optional)
- [ ] 💾 **Choose a contributor interested** You can choose someone interested that will be able to solve your issue

#### If you want to contribute and be rewarded
- [ ] 💾 **A contributor is interested** You can show interest on the task page clicking in "I'm interested"
- [ ] 💾 **You can offer** You can make an offer
- [ ] 🔀 **You can be assigned**. You can be assigned, you should work on the task and send a Pull Request.
- [ ] 💬 **Review** Ask in comments for a review :)
- [ ] 🏁 **Approved** Once approved you will receive your payment

### 📋 Task status
- [x] ***OPEN***
- [ ] ***IN PROGRESS***
- [ ] ***DONE***

### Good to know

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. For a more compreenhensive guide to create the Pull Request properly, you can access: https://guides.github.com/activities/hello-world/

3. You can [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/)

### 🤔❓ Questions
Leave a comment below!
This issue was a comment made by our GitpayBot [Gitpay Bot](https://github.com/gitpaybot).

**Comment by GitpayPop** [comment]
A bounty of *4 USD* was added to this issue. See task on [GitPay](https://gitpay.me/#/task/612)

**Comment by Houkime** [comment]
Hi, i want to migrate my acc to a gts instance, but i am currently blocked by the lack of `alsoKnownAs`.
Am i correct to assume that one can look up the json-ld schema to feed into astool here?

https://github.com/w3c/activitystreams/commit/54a6723ed1c8b95a12997b4e73100308e267fc8f

Also, activity lib looks unmaintained atm.

**Comment by natemoo-re** [comment]
I'd be very interesting in helping out with this!

**Comment by tsmethurst** [comment]
> I'd be very interesting in helping out with this!

Noted, thank you :) it'll be a while, bunch of other stuff to do first

**Comment by blakesmith** [comment]
@tsmethurst Saw you just grabbed this one. Let me know if you need any help, happy to help however I can!

**Comment by tsmethurst** [comment]
Thanks for the offer :) I'll be picking this up after our Christmas break (so, start of January).

**Comment by tsmethurst** [comment]
> Also, activity lib looks unmaintained atm.

@Houkime We maintain a fork here: https://github.com/superseriousbusiness/activity

**Comment by mkarliner** [comment]
Just created my gts instance so, I'll be testing the migration from my masondon instance as soon as it's ready.

**Comment by tsmethurst** [comment]
Moving this back to the 0.15.0 milestone as there's quite a lot of complicated moving parts to get this right, and we decided we'd rather take plenty of time to ensure it works properly instead of putting it in a release too soon without sufficient testing. It's a v. high stakes feature, as a bodged Move could mean that you lose your relationships with followers/following, so it's crucial we test this sufficiently, because we don't people to mess up their accounts. You'll have to hold your horses a little longer! :hand: :horse:

**Comment by blakesmith** [comment]
@tsmethurst Thanks for your care and thoughtfulness! Definitely a feature you want to get right. Appreciate all you do!

**Comment by tsmethurst** [comment]
Thanks, that's sweet :)

**Comment by tsmethurst** [comment]
Moving your account is now implemented on main. Currently only followers are moved, other things like following, blocks, etc, are not. We'll add some endpoints for import/export of such things as we go along. Once Move is in a release, I'll close this issue :)

**Comment by gytisrepecka** [comment]
These are great news 👏

I'm sorry if that has been already answered before, but does this include moving from GoToSocial (e.g. to Mastodon), or moving to GoToSocial (e.g. from Mastodon)? Maybe both?
