### ISSUE TITLE
[feature] alternative to pinafore as supported/tested client

### ISSUE THREAD

**Issue by adammathes** [superseriousbusiness/gotosocial#1343]
### Is your feature request related to a problem ?

I love that GotoSocial imlpements the mastodon client interface so there's a wide variety of options to use!

I have been primarily using pinafore on the web, but saw that as of 1/9/2023 it is unmaintained software - see https://nolanlawson.com/2023/01/09/retiring-pinafore/

While the static pinafore.social still works, I expect there may be issues in the future, and we can't expect new features etc. 

### Describe the solution you'd like.

Given that change, it may be worth considering pointing to another web client as the suggested starting point.

(I am trying out a few now but have no specific suggestion in mind for compatability, I've only recently started running my own GotoSocial instance.)

### Describe alternatives you've considered.

- Wait and see if a friendly, supported fork of pinafore emerges and switch to that
- Forks and bundle pinafore with GTS, taking on maintenance burden to ensure it's up to date and compatible with GTS. Enable GTS to serve a local/authenticated version
- Include another mastodon web FE as part of GTS to ensure a default end-to-end tested client works out of the box (like pleroma FE?)

### Additional context.

Reading through the contrib docs it suggests using a local pinafore instance as part of a testrig, is it worth reconsidering what the suggested test client is as well?

**Comment by tsmethurst** [comment]
The pinafore github repo won't be going away, so I think it's still fine to suggest that as a local testing client for a while.

Same for the web frontend: I don't think we need to be in a hurry to suggest something else, since pinafore.social still works fine, and likely will continue to work fine.

For other web clients, I did start messing about with https://elk.zone, which seems like it might be a good successor. Already found a few issues with that that we need to squash.

**Comment by SanchayanMaity** [comment]
May be the new fork semaphore.social can be recommended in place of pinafore. https://github.com/NickColley/semaphore
