### ISSUE TITLE
[bug/0.7.0-rc1] Table misalignment on smaller screens in bulk federation UI

### ISSUE THREAD

**Issue by turtlegarden** [superseriousbusiness/gotosocial#1438]
### Describe the bug with a clear and concise description of what the bug is.

When loading the bulk federation UI on mobile or a smaller screen, the table goes out of bounds resulting in an ugly UI glitch.

![The described graphical glitch above](https://user-images.githubusercontent.com/52264162/217053511-2613bd03-3b5f-40bd-810b-c8df9dd09b73.png)

### What's your GoToSocial Version?

v0.7.0 rc

### GoToSocial Arch

amd64 Binary

### Browser version

Bromite 108

### What happened?

The table does not fit in its bounds, and creates horizontal scroll on the page.

### What you expected to happen?

The table should fit in bounds or scroll.

### How to reproduce it?

Open the bulk federation UI on a small screen.

**Comment by turtlegarden** [comment]
Oh, it also appears this happens with the instance table.

![Screenshot_20230208-205707](https://user-images.githubusercontent.com/52264162/217908280-a2a7f6f8-042b-4388-bc2f-c1a8a97876df.png)

**Comment by daenney** [comment]
Was this fixed by #1436 for you?

**Comment by f0x52** [comment]
Huh, missed this when I triaged issues on monday. Might be useful if we had an issue template for frontend bugs so they can get the label automatically 

> Was this fixed by #1436 for you?

Wouldn't think so, since those just applied to the public listing page. I've been trying to avoid horizontal scroll but for this part of the design wrapping would make it super messy, so scroll is preferable I think

**Comment by turtlegarden** [comment]
yeah, i think only horizontal scroll for tables is good. tables work well with it imo but not really anything else
