### ISSUE TITLE
[bug] host-meta endpoint needs to be implemented and used in search

### ISSUE THREAD

**Issue by anantshri** [superseriousbusiness/gotosocial#1558]
### Describe the bug with a clear and concise description of what the bug is.

It seems host-meta endpoint is used to find the direction for webfinger location. Tested this across different instances except pleroma lots of major systems have implemented it as shown in the screenshot.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/236843/221377915-ebb88fb7-db6b-4407-9cc8-cfd5b99dbb49.png">

we dont have this end-point right now but feels like this should not be a lot of work https://docs.joinmastodon.org/dev/routes/#host-meta is the reference i could find. 

### What's your GoToSocial Version?

0.7.0

### GoToSocial Arch

amd64

### What happened?

I was trying to follow someone. that person had host-meta as a url pointer for webfinger but didnt had webfinger redirection on website.

### What you expected to happen?

find the person and follow them

### How to reproduce it?

host which has following conditions met
1. web domain is different from user domain.
2. webfinger of user domain is not redirected to web domain
3.  host-meta on user domain points to correct webfinger spec url.

if we try to follow this person via gotosocial gts will not be able to find the user as it directly attempts to access webfinger end point.

### Anything else we need to know?

https://mastodon.rfc1925.org/@ondrej/109926688806310155 this is the reference post for the same

**Comment by anantshri** [comment]
we need to do two things. one expose our own host-meta and use host-meta to find webfinger url

**Comment by daenney** [comment]
I'm a bit torn about this one. The whole idea of webfinger being on a .well-known is that it's safe to assume `domain.tld/.well-known/webfinger` and that that endpoint should somehow be functional.

I would argue that if you're using `domain.tld` for your fediverse instance and `domain.tld/.well-known/webfinger` doesn't work it's a bug. I can see `host-meta` being useful in skipping potentially one of a few redirects, but not at least redirecting that endpoint seems like a misconfiguration. The webfinger RFC also doesn't require usage of host-meta as it registers the endpoint directly in the IANA well-known registry.

By that same logic, the client shouldn't have to go through host-meta to find the webfinger endpoint for a domain.

**Comment by anantshri** [comment]
i would have been in full agreement with @daenney till yesterday. yesterday encountered this profile which is very well searchable and discoverable on mastodon instances but not on gts instances which made me question. and when i checked other fediverse softwares most seems to have this implemented. 

so 
1. i dont see any harm in exposing that end point from our side. (Well to a non coder of project everything seems non harmful, so take this with that consideration in mind)
2. I can see this as a potential problematic scenario to implement while searching or discovering users from gts thats the angle where my suggestion would be to check for webfinger if that endpoint is not working then check host-meta to see if alternative webfinger exists before we call it as not found.

**Comment by daenney** [comment]
> 1. i dont see any harm in exposing that end point from our side. (Well to a non coder of project everything seems non harmful, so take this with that consideration in mind)

I agree with that. It's a very simple endpoint. That said, it does need to be available on `domain.tld`. So even if we add it, if `host` and `account-domain` aren't the same and the admin forgets to proxy that endpoint it's still sadness :disappointed:.

We'll need to make sure we add that to the docs in that case. I'm starting to feel like we should have some kind of "validate-federation" command or something that ends up checking if things look fine from the outside. That might also be usable against a different instance entirely to maybe help figure out what is going wrong.

> 2. I can see this as a potential problematic scenario to implement while searching or discovering users from gts thats the angle where my suggestion would be to check for webfinger if that endpoint is not working then check host-meta to see if alternative webfinger exists before we call it as not found.

Yup, I think that's fine too. It's reasonable for us to assume webfinger is where it should be. If it's not we can try and resolve it through host-meta.

**Comment by tsmethurst** [comment]
https://github.com/superseriousbusiness/gotosocial/issues/1445 might be related, but not 100% sure.

**Comment by daenney** [comment]
Specifically related to that RFC1925.org domain, they're just broken:

```
$ curl https://mastodon.rfc1925.org/.well-known/host-meta
<?xml version="1.0" encoding="UTF-8"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
  <Link rel="lrdd" template="https://mastodon.rfc1925.org/.well-known/webfinger?resource={uri}"/>
</XRD>
```

But then:

```
$ curl -I https://mastodon.rfc1925.org/.well-known/webfinger
HTTP/2 400 
```

Regardless of implementing looking up webfinger endpoints through host-meta, that instance will never work.

**Comment by daenney** [comment]
Sorry, disappeared my comment about the RFC1925 well-known not working. Seems I was hitting some issue because it's fine now.

**Comment by daenney** [comment]
Alright, so Dolphin Emu has the issue described here, which explains why I couldn't search for them either :smile:. Their instance is using `dolphin-emu.org` and the handle is `@dolphin@dolphin-emu.org`.

(I've removed a bunch of things curl outputs that isn't pertinent to the issue)

```
$ curl -v 'https://dolphin-emu.org/.well-known/webfinger?resource=acct:dolphin@dolphin-emu.org'
> GET /.well-known/webfinger?resource=acct:dolphin@dolphin-emu.org HTTP/2
> Host: dolphin-emu.org
> user-agent: curl/7.88.1
> accept: */*
> 
< HTTP/2 404 
< content-type: text/html; charset=iso-8859-1
< content-length: 196
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
</body></html>
* Connection #0 to host dolphin-emu.org left intact
```

Now, lets grab host-meta:

```
$ curl https://social.dolphin-emu.org/.well-known/host-meta
<?xml version="1.0" encoding="UTF-8"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
  <Link rel="lrdd" template="https://social.dolphin-emu.org/.well-known/webfinger?resource={uri}"/>
</XRD>
```

So there we go, redoing the request:

```
$ curl -v 'https://social.dolphin-emu.org/.well-known/webfinger?resource=acct:dolphin@dolphin-emu.org'

> GET /.well-known/webfinger?resource=acct:dolphin@dolphin-emu.org HTTP/2
> Host: social.dolphin-emu.org
> user-agent: curl/7.88.1
> accept: */*

< HTTP/2 200 
< server: nginx
< date: Sun, 26 Feb 2023 14:18:21 GMT
< content-type: application/jrd+json; charset=utf-8

{"subject":"acct:dolphin@dolphin-emu.org","aliases":["https://social.dolphin-emu.org/@dolphin","https://social.dolphin-emu.org/users/dolphin"],"links":[{"rel":"http://webfinger.net/rel/profile-page","type":"text/html","href":"https://social.dolphin-emu.org/@dolphin"},{"rel":"self","type":"application/activity+json","href":"https://social.dolphin-emu.org/users/dolphin"},{"rel":"http://ostatus.org/schema/1.0/subscribe","template":"https://social.dolphin-emu.org/authorize_interaction?uri={uri}"}]}
```

Now, if we try to lookup an account that doesn't exist:

```
$ curl -v 'https://social.dolphin-emu.org/.well-known/webfinger?resource=acct:fake@dolphin-emu.org'
> GET /.well-known/webfinger?resource=acct:fake@dolphin-emu.org HTTP/2
> Host: social.dolphin-emu.org
> user-agent: curl/7.88.1
> accept: */*

< HTTP/2 404 
< content-type: text/html
* Connection #0 to host social.dolphin-emu.org left intact
```

This raises a thing. If we do a webfinger query and we get a 404 we can't truly distinguish between "webfinger is not here, go find it through host-meta" and "webfinger is here but account you queried for doesn't exist".

Given that both 404s also returned with content-type HTML we can't really distinguish them. The only possibility would be using the absence of a response body on the 404 to :crystal_ball: that we've actually not hit the webfinger server. That doesn't work for GtS though which will either return an HTML or JSON body on a not found user instead of the empty response Mastodon seems to be doing.

It would mean that in all cases where we get a 404 we'd end up doing a secondary request to host-meta to find if the webfinger URI is different or not and then potentially issue another request. That's doable but if we end up repeat searching within the same domain, it would be nice if we could remember the webfinger endpoint for a while.

Based on looking at the code, we only call `transport.Finger` through https://github.com/superseriousbusiness/gotosocial/blob/55300cbd7395daa7db4d4393a2b990e7b986af53/internal/federation/dereferencing/account.go#L157

I suppose that in `fingerRemoteAccount` we could retrieve the `gtsmodel.Instance` and check for the webfinger URI. Then we use that one or the default of constructing it based on the domain. If the constructed one fails we'd then query host-meta and see if we get another URI and try that. We should store when we've last done the host-meta lookup in that case and not bother retrying host-meta for like 24hrs or something?

We could also store this on the account model I suppose but it's distinctly an instance level thing afaik so that feels kinda wrong?

**Comment by daenney** [comment]
If we do the webfinger endpoint lookup as part of `GetRemoteInstance` then I think in `fingerRemoteAccount` we could always pull it out of the DB? As long as we refresh it every now and then?

**Comment by tsmethurst** [comment]
Good questions. To me the following would make the most sense:

1. Try to lookup using constructed webfinger endpoint first (works in like 90% of cases).
2. If that fails, try to get webfinger endpoint from host-meta.
3. Whatever the result of the host-meta lookup, cache it in an in-memory cache somewhere (positive or negative hit).
4. If we got a host-meta result, use that.
5. Next time a lookup occurs for this domain, check if a cache entry exists for it. If a positive hit, use the host-meta webfinger endpoint. If a negative hit, fail since we know the endpoint won't be found.

To avoid repeating calls, we can make this cache like 24 hours or something. Having it as an in-memory cache also recognizes that the endpoint might change / remote admins might fix their setup, and users can just try again later.

What do you think?

**Comment by daenney** [comment]
Ah yes, that sounds more sensible. I hadn't considered the in-memory cache, I like that a lot more.

**Comment by daenney** [comment]
I've looked at this a bit more and I'm wondering what we should cache. Right now, with the exception of the domain block cache, everything else that we cache is a `gtsmodel` which at least in practice always seems to get serialised to the DB. That last thing isn't something we want here.

Currently I'm thinking of it as adding a `hostmeta` to our `gtsmodel` package in the same spirit as all the other models, just without the `bun` tags. Then we'd add a cache to `gtsCaches` like we do for everything else and a `HostMeta` method on the `GTSCaches` interface?

However, then my next question. The current pattern seems to be we normally only interact with any of the caches from `internal/db`, which in this case wouldn't come into play. But the way we access `state` and through there the cache is currently always done by the struct in the `internal/db/bundb` packages which gets initialised by `NewBunDBService`. What makes sense to do in this case?

**Comment by NyaaaWhatsUpDoc** [comment]
My thoughts would be to add a `State.Caches.HostMeta` cache. And then add a reference to `*State` within either the `Dereferencer` or `Transport`. And then on each call you'd do:

```
state.Caches.HostMeta.Load("", func() (*HostMeta, error) {
    // host-meta lookup logic goes here
}, uri)
```

the plan is to eventually move all the caches to the `State.Caches` struct, because in time it makes it easier sharing cache access in other areas (e.g. if we need to invalidate values from cache), it's useful keeping them all in the same place, and it allows cycling / including them in tests a lot easier :)
