### ISSUE TITLE
[feature] data protection: do not log IPs

### ISSUE THREAD

**Issue by margau** [superseriousbusiness/gotosocial#1574]
### Is your feature request related to a problem ?

According to the principle of data economy, it would be nice to reduce the amount of personal data stored.
Currently, IPs are logged as part of the access log.

### Describe the solution you'd like.

Add an option to obfuscate/skip IPs, alternatively only log them related to error and/or warning logs.

### Describe alternatives you've considered.

NONE

**Comment by daenney** [comment]
I think we should look at this but I'd like us to consider a couple of things. Whatever we do here, it's important to note that none of this matters if you don't trust your instance admin (who incidentally also has access to the DB, the host OS etc). There's also no way for a user to verify what the admin has configured or where else these logs may still go, what (other) data sets they may be combined with that would defeat not emitting the client IP on our side entirely etc.

With that said:
* I don't think we should obfuscate IPs. If the admin has the logging of IPs on we should assume they do so for good reason and not partially obstruct their view. If someone wishes to retain logs long term the responsible thing to do is redact that information for example during log ingestion. How to redact them (for example round them up to the nearest /24) is also very dependent on need and can vary based on jurisdiction. For those reasons I don't think redaction/obfuscation is something we should take on and instead have that handled through external tools that are built for this
* I don't think turning IP address logging on or off should be based on the log level. It should be a configuration value. If I chose to explicitly set it to off I might omit things during central log ingestion like obfuscating or redacting the IP believing that that information is never contained in the logs. Having a situation that implicitly results in the IP getting logged but only under certain conditions like the log level may result in this information getting retained against the knowledge and intent of the admin
* Since we have the request ID nowadays it's very simple for someone to correlate a request from a load balancer (where they may log the client IP still) and GtS on the backend if they have a need to do so. This means that turning off logging the client IP in GtS doesn't hinder day to day operation and debugging much but does result in one less source of logs that contain IPs to worry about. That's a good thing and why I think disabling client IP logging entirely is worthwhile to implement

**Comment by daenney** [comment]
I would suggest we keep the current default. It's pretty normal to log the client IP, especially in the case where GtS might be running in non-proxied mode. We could infer it based on `trusted-proxies` but that's bound to be a mess. This feels like an appropriate thing to call out in our configuration guides.

On logging the IP itself; @NyaaaWhatsUpDoc and I recently added the hook thing to the logger. My gut feeling is we should be able to use that to then have the logging middleware install an additional hook or not that logs the client IP. That should be doable in a one-off kind of way.

**Comment by moan0s** [comment]
Just a quick comment: While ofc trust in the instance admin is needed there are certain cases where trusted admins can prevent data leaks that would harm users by turning of IP address logging (e.g. police confiscating the server).

**Comment by tsmethurst** [comment]
>  there are certain cases where trusted admins can prevent data leaks that would harm users by turning of IP address logging (e.g. police confiscating the server).

Yes good point :)
