### ISSUE TITLE
[feature] Allow remapping of S3 endpoint to S3_ALIAS_HOST

### ISSUE THREAD

**Issue by vivithecanine** [superseriousbusiness/gotosocial#1632]
### Is your feature request related to a problem ?

In Mastodon there is the concept of a [`S3_ALIAS_HOST`](https://docs.joinmastodon.org/admin/optional/object-storage-proxy/) which allows you to define a server that proxies media traffic toward a backend object store, this allows for flexibility to migrate from Amazon S3, to Wasabi, to Backblaze, and self-hosted MinIO and so on without breaking messages for akkoma other non-caching federated servers

### Describe the solution you'd like.

I would like to be able to provide a static hostname that maps to a generic s3 bucket

When an ActivityPub message is published, or copied from another server with media, use the alias host defined in an env var like `GTS_S3_ALIAS_HOST` or in the config file as `s3-alias-host:` instead of the `StorageS3Endpoint`, if defined

### Describe alternatives you've considered.

NONE

**Comment by LittleFox94** [comment]
So `S3_ALIAS_HOST` would be used every time an object storage URL is given to the outside world, e.g. by redirect of the fileserver, while GTS itself connects to the `StorageS3Endpoint` to store and fetch objects as it already does?

Could it be useful to define a `S3_ALIAS_URL_PREFIX`, so more than just the host to allow e.g. configuring `https://gts.example.com/s3/aws/`, which will then rewrite `https://$whatever_s3_host/some/object/url` to `https://gts.example.com/s3/aws/some/object/url`?

I'd definitely like the option to have different protocols for S3 endpoint and published S3 URLs, in my case this would allow GTS to connect to my internal Ceph `radosgw` instances directly, instead of going through the reverse proxy (which is needed for external things to access my S3).

**Comment by daenney** [comment]
I'm going to close this in favour of #2574 where we've got the generic solution and different use cases documented. If you're still interested in this feature, feel free to subscribe to that issue.
