### ISSUE TITLE
[bug] Client Compatibility : Ebou Mac Client

### ISSUE THREAD

**Issue by anantshri** [superseriousbusiness/gotosocial#1662]
### Describe the bug with a clear and concise description of what the bug is.

Ebou client https://terhech.de/ebou/ when attempting to login performs following steps correction.
1. Identifies the URL as a valid fediverse instance, 
2. Opens the authentication prompt
3. GTS provides the out of band token
4. Ebou provides an option to provide out of band token and click connect 
5. when you click connect, following error is received.
![image](https://user-images.githubusercontent.com/236843/229166491-b8142e6b-deaf-4039-ab4f-32f7553a9dae.png)

### What's your GoToSocial Version?

0.7.1

### GoToSocial Arch

amd64

### What happened?

Ebou client https://terhech.de/ebou/ when attempting to login performs following steps correction.
1. Identifies the URL as a valid fediverse instance, 
2. Opens the authentication prompt
3. GTS provides the out of band token
4. Ebou provides an option to provide out of band token and click connect 
5. when you click connect, following error is recieved.

### What you expected to happen?

user login

### How to reproduce it?

Ebou client https://terhech.de/ebou/ when attempting to login performs following steps correction.
1. Identifies the URL as a valid fediverse instance, 
2. Opens the authentication prompt
3. GTS provides the out of band token
4. Ebou provides an option to provide out of band token and click connect 
5. when you click connect, error is recieved.

**Comment by daenney** [comment]
The `languages` key exists in the Instance entity in the Mastodon API since version 4.0.0 only, which was released on November 14th 2022. I'm honing in on that one since that's the only endpoint it could sensibly be checking as part of the login flow.

Ebou is likely broken with plenty of other implementations too, since it seems they're parsing the response on `/api/v1/instance` with the assumption that `languages` is present, but that's only true on `/api/v2/instance best I can tell.

The Mastodon docs are a bit weird on this as they say /api/v2/instance returns a V1:Instance which has `languages` as mandatory, but notes it was only added in 4.0.0. I think this is a confusing representation in the docs, as you can't add mandatory fields like that to V1:Instance since that's a backwards incompatible change.

This is a bug in Ebou and not something we should fix in GtS. Best I can see our responses on /api/v1/instance and /api/v2/instance are what they should be. Ebou should more permissive when it comes to parsing the responses and probably handle the absence of keys it cares about by defaulting them to something, like `languages: ['en']`.

**Comment by rjp** [comment]
Looking at https://docs.joinmastodon.org/entities/V1_Instance/ (which is returned from /api/v1/instance according to https://docs.joinmastodon.org/methods/instance/), it looks like `languages` was added in 2.3.0 (March 2018)?

You might be confusing the Instance types since the non-v1 Instance (returned from /api/v2/instance) was added in 4.0.0.

Unless I'm reading the API docs wrongly!

**Comment by daenney** [comment]
Mmm nope, I might've gotten confused honestly. Going over it again I seem to reach the same conclusion you did.

The docs are incredibly frustrating to explore and understand. I'm looking a bit at what other things are doing and they do seem to all return a `languages` key on v1 too. This thing with adding mandatory keys to responses without incrementing the API versions is annoying.

I'll take a look at fixing that in GtS then!

**Comment by rjp** [comment]
> The docs are incredibly frustrating to explore and understand.

100% agree.
