### ISSUE TITLE
[bug] Unfollowing throws error

### ISSUE THREAD

**Issue by moan0s** [superseriousbusiness/gotosocial#1819]
### Describe the bug with a clear and concise description of what the bug is.

When I (on `0.8.1`) try to unfollow an account on` 0.9.0-rc2`  I get `MastoDeserializeError: Unknown content type text/html returned from the server.` in phanpy.social or a non-descriptive error message in Tusky

### What's your GoToSocial Version?

0.8.1 git-4dbf9a2 bzw. GoToSocial 0.9.0-rc2 git-2063d01

### GoToSocial Arch

Docker

### What happened?

Upon unfollow, error pops up

### What you expected to happen?

No error, sucessful unfollow

### How to reproduce it?

* Use an account on 0.8.1 and follow an account on 0.9.2-rc2
* Try to unfollow

### Anything else we need to know?

Tested for a `account domain != host` setup on part of the following server

**Comment by tsmethurst** [comment]
Mmm the only thing we're really able to tell here is that the remote server is returning an error, but not a type that the client is able to understand, because it's returning the error as text/html. This is already kind of curious, because I thought in 0.9.0-rc2 we'd fixed the error handling to return JSON the majority of the time.

Apart from that, it's hard to tell what's actually happening, because there's no HTTP code or anything. I'll try to reproduce by unfollowing one of my own accounts.

**Comment by moan0s** [comment]
Well, I tried to reproduce it and - it worked? I pretty sure I did everything the same. Closing this issue, sorry :/
