### ISSUE TITLE
[bug] gotosocial.service doesn't start server

### ISSUE THREAD

**Issue by meljoann** [superseriousbusiness/gotosocial#1916]
### Describe the bug with a clear and concise description of what the bug is.

When I start the server with ./gotosocial command, everything works. But  gotosocial.service won't start the server.

Error message from journalctl:
`gotosocial.service: Main process exited, code=exited, status=1/FAILURE`

Error in /var/log/gotosocial.log
`error executing command: error creating instance account: ERROR: column account.status_format does not exist (SQLSTATE 42703)`

When I looked at the list of tables with psql, there was an "accounts" table but no "account" table.

Columns in "accounts" included "status_content_type", but not "status_format"

### What's your GoToSocial Version?

0.9.0

### GoToSocial Arch

amd64 binary

### What happened?

The command
`sudo systemctl enable --now gotosocial.service`
failed to start the gotosocial server.

### Anything else we need to know?

I've used the default gotosocial.service provided, and other defaults the same as in installation instructions.

I'm on Debian 11, VPS.

**Comment by meljoann** [comment]
No idea if it is really a bug, or me not knowing what I'm doing ,p

**Comment by tsmethurst** [comment]
I've got a feeling this is due to `./gotosocial` and the gotosocial service looking in different places for their config.yaml file. It also looks like some database migrations have not run properly, did you interrupt them? :thinking:

**Comment by meljoann** [comment]
Oh brilliant, thanks for the clues. Will look tomorrow. Database migrations... I probably did a ctrl-c when I shouldn't have haha

**Comment by tsmethurst** [comment]
If you haven't actually used your instance at all yet, or seen/searched any other accounts, it might not be a bad idea to just drop your db and create it again, and ensure you don't interrupt any migrations, because that will seriously break your instance in the long term..

**Comment by meljoann** [comment]
Amazing, thanks Tobi. I actually was trying to do that today too but must have fecked it up 😂

**Comment by tsmethurst** [comment]
no problem -- just make sure you didn't use the instance to federate at all yet, or you will have federation issues!

**Comment by daenney** [comment]
I think an issue you can run into if you start it through `systemctl` the first time is that because of the migrations it needs to run it feels like the command is hanging as it can take a bit to complete. Which can prompt people to Ctrl-c potentially triggering this scenario. On an empty DB this shouldn't take very long though, but I guess that depends a bit on the speed of hardware etc. Another possible situation is if there's a `TimeoutStartSecs` configured either in the systemd unit file or for systemd as a default and the migration takes longer at which point systemd will have killed the process.

If like Tobi says you haven't federated at all, as in this is a new installation and you never got around to creating a user or following someone/being followed, then it's safe to drop the DB and initialise it from 0. 

What you can do the first time is first become the gotosocial user `su gotosocial` or `sudo -u gotosocial`, switch to the directory `cd /gotosocial` and then run `/gotosocial/gotosocial --config-path config.yaml server start` like in the systemd unit file. At that point, follow along with the logs at startup and you should see it running migrations and when it's done. It'll say so explicitly, but you can also look for a line like `func=router.(*router).Start.func5 level=INFO msg="listening on 127.0.0.1:9200"` at which point we've started the HTTP server so we know the database migrations have completed.

After that it's safe to ctrl-c the process and let it cleanly shut down, then start it using `systemctl` like normal.

**Comment by meljoann** [comment]
Aw thanks Daenney & Tobi. That's so helpful. Will have another crack at it tomorrow

**Comment by meljoann** [comment]
yayy it worked! thanks so much for all your help.
one major thing I did wrong the first time was install it in /root/, so the permissions were all messed up...
