### ISSUE TITLE
[bug] new account not searchable

### ISSUE THREAD

**Issue by meljoann** [superseriousbusiness/gotosocial#1955]
### Describe the bug with a clear and concise description of what the bug is.

My first account works fine and is federating. 

I created a second account. I'm able to interact with it from the first GTS account, but it didn't show up in searches from Mastodon.

In Semaphore/Pinafore, the first account shows its URL correctly when I hover over the account name. But in the second account shows:
https://localhost and then /"correct account name"

Daenney has tried:
curl -X GET 'https://myDomain.org/.well-known/webfinger?resource=acct:@myAccount@myDomain.org' | jq .

And we just got a load of:
https://localhost/

### What's your GoToSocial Version?

0.9.0

### GoToSocial Arch

amd64 binary

### What happened?

First account is fine, second account is using "localhost" instead of my host name.

### Anything else we need to know?

config file is set as below, not changed since installation:
host: "social.gravitons.org"
account-domain: ""

**Comment by daenney** [comment]
For context, I had a chat with @meljoann and something's really surprising to me.

Their own account works fine when webfingered, but the new accounts have the localhost thing in them:

```json
$ curl -X GET 'https://social.gravitons.org/.well-known/webfinger?resource=acct:@mmmeljoann@social.gravitons.org' | jq .
{
  "subject": "acct:mmmeljoann@social.gravitons.org",
  "aliases": [
    "https://social.gravitons.org/users/mmmeljoann",
    "https://social.gravitons.org/@mmmeljoann"
  ],
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://social.gravitons.org/@mmmeljoann"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://social.gravitons.org/users/mmmeljoann"
    }
  ]
}

```
```json
$ curl -X GET 'https://social.gravitons.org/.well-known/webfinger?resource=acct:@gravitons@social.gravitons.org' | jq .
{
  "subject": "acct:gravitons@social.gravitons.org",
  "aliases": [
    "https://localhost/users/gravitons",
    "https://localhost/@gravitons"
  ],
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://localhost/@gravitons"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://localhost/users/gravitons"
    }
  ]
}
```

I'm not really sure how that would happen, bar `host` or `account-domain` being set to `localhost`. Since I'm able to successfully follow the first account, I'm also fairly certain the DB didn't get generated with `host: localhost` at first, as shown by a finger of the instance account:

```json
curl -X GET 'https://social.gravitons.org/.well-known/webfinger?resource=acct:@social.gravitons.org@social.gravitons.org' | jq .
{
  "subject": "acct:social.gravitons.org@social.gravitons.org",
  "aliases": [
    "https://social.gravitons.org/users/social.gravitons.org",
    "https://social.gravitons.org/@social.gravitons.org"
  ],
  "links": [
    {
      "rel": "http://webfinger.net/rel/profile-page",
      "type": "text/html",
      "href": "https://social.gravitons.org/@social.gravitons.org"
    },
    {
      "rel": "self",
      "type": "application/activity+json",
      "href": "https://social.gravitons.org/users/social.gravitons.org"
    }
  ]
}
```

So I'm a little confused as to how this could happen.

**Comment by meljoann** [comment]
omg ok. figured it out, i had a gotosocial folder from a previous installation attempt with a crappy config.yaml

tried the create user command with the correct config path and everything is great now. :)

**Comment by meljoann** [comment]
closing...

**Comment by daenney** [comment]
Hah. OK. We should implement a check for this. Once the DB has been initialised we can use the domain for the instance account to verify account/host domains match and throw an error when they don't. That should also catch case where someone initialised the DB before changing that value.

**Comment by daenney** [comment]
So I think the problem ended up coming from here https://github.com/superseriousbusiness/gotosocial/blob/2a99df0588e168660d3b528209d8f51689ca92b7/internal/uris/uri.go#L131

Because the `config.yaml` that was pointed at had `host: localhost` set, but still had valid DB credentials, we ended up generating account URIs with `localhost`. In that function we don't have access to the DB so it's hard to verify it with the instance account at that point as a double check. But it's called in `adminDB.NewSignup`, so we could potentially do the check there on the result.

Alternatively, we could do a check like this early in command startup. That would also be useful for the server, to avoid the footgun of someone changing the values afterwards.
