### ISSUE TITLE
[question] Search scope

### ISSUE THREAD

**Issue by xnuk** [superseriousbusiness/gotosocial#2002]
> With this release, you can now also do partial text searches for:
> - statuses you've posted yourself (search in status content warning and body)
> - statuses posted in reply to you (search in status content warning and body)
> - accounts you don't yet follow (search in username and display name)
> - accounts you do follow (search in username, display name, and bio)

Looking over [v0.10.0-rc1 release note] and #1836, I found limiting search to my statuses and replies only is 'intentional'. Personally this is the most single thing I don't like from mastodon - I want to search whatever I never noticed. Despite I could use it with making a fork excluding the related codes anyway, but I would like to ask:
- if this (limiting search related to myself only) is a way GoToSocial wants to go (and contexts?)
- or any chance to get an option to configure this

aaaaand documenting this stuff.

[v0.10.0-rc1 release note]: https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.10.0-rc1

**Comment by VyrCossont** [comment]
Extending out-of-box search to users and posts that *explicitly* opt into searchability would be a nice upgrade that's in the spirit of the GtS project. Mastodon has [the `discoverable` flag](https://docs.joinmastodon.org/spec/activitypub/#discoverable) for users, and iirc it's been adopted by other projects, but the only shipped opt-in mechanism for posts that I'm aware of is [Fedibird's `fedibird:searchableBy`](https://github.com/mastodon/mastodon/pull/23808#issuecomment-1543649425), which is not widely deployed. Still, we might consider adding `fedibird:searchableBy` to GtS as well.

Still, I'd really like an option for broader search scope too.

**Comment by tsmethurst** [comment]
This first version of search (which we called 'partial' text search to differentiate it from 'full' text search) is basically just aimed at making it easier for you to find your own statuses without having to scroll all the way down through your profile looking at them.

Search and indexing of posts is a touchy subject in the fedi -- for good reason -- and we're very mindful of folks' privacy regardless, so for any search stuff we end up implementing, we've gotta do a lot of thinking first about potential harassment vectors (the classic: searching for a term like 'black' or 'queer' on a large widely-federated instance and then brigading the OP).

So it's not that this is the 'final' implementation and we'll go no further, but rather this is an initial uncontroversial foray into making it easier for user's to at least find their own statuses, and replies to their statuses. We'll likely look in future for a way of letting people opt-in to make all of their posts searchable, and/or making them searchable on a post-by-post basis, in a strictly opt-in way so that they can be wary up-front of what the consequences might be.

**Comment by tsmethurst** [comment]
Gonna close this since the question is answered, but feel free to reopen if you have follow-up questions :)
