### ISSUE TITLE
[bug/investigation] Slow DB query selecting statuses using specific emoji

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2015]
From an email:

> You can run the following query by
> hand and see a HUGE delay:
> 
> timestamp="22/07/2023 01:01:04.170" func=bundb.queryHook.AfterQuery
> level=WARN duration=16.497780301s query="SELECT \"id\" FROM \"statuses\"
> WHERE ('01WK9MJ69CGFHT4D9H3RAZKHKY' IN (emojis))" msg="SLOW DATABASE QUERY"
> 
> (My instance has about a million rows in the statuses table.)
> 
> This still happens on rc3.  This abort was after 16.5 seconds, but it
> actually takes > 1 minute (maybe more than the DB timeout config value).
> The service grinds to a halt, and my hosting provider emails me about
> pegged CPU.

**Comment by NyaaaWhatsUpDoc** [comment]
this actually works out much faster doing `SELECT id FROM statuses WHERE emojis LIKE "%01WK9MJ69CGFHT4D9H3RAZKHKY%"`. (some recent code i added does this). i'm going to do some investigating into why specifically, but i think it's to do with it needing to scan the whole table and for every single entry it has to marshal that `emojis` column data into an array of strings and then iterate over this. whereas using a LIKE it can skip the marshaling step.

**Comment by NyaaaWhatsUpDoc** [comment]
after testing on my own database of 3 million statuses, neither is ideal!

**Comment by NyaaaWhatsUpDoc** [comment]
After discussion on Matrix, it turns out we already have a status-emoji relational table, which we had originally slated for deletion. But it seems it's time for it to come out of retirement!

The largely effected function is the `DeleteEmojiByID()` database function, which while mostly used in background cleanup tasks, is also used used during... well, any emoji delete operation.

**Comment by NyaaaWhatsUpDoc** [comment]
Working on this now :+1:
