### ISSUE TITLE
[bug] Some Mastodon APIs require authentication when not neccesary

### ISSUE THREAD

**Issue by ToadKing** [superseriousbusiness/gotosocial#2038]
### Describe the bug with a clear and concise description of what the bug is.

I've been trying to get GoToSocial to work with [FediFetcher](https://github.com/nanos/FediFetcher) and it looks like all the Mastodon APIs we use for fetching remote statuses all return 401 errors when trying to do so on GoToSocial servers.

The ones we FediFetcher specifically on remote servers without authentication are these:
* accounts/{id}/statuses
* accounts/lookup
* statuses/{id}/context

Is it possible for those APIs to work without requiring an access token?

### What's your GoToSocial Version?

v0.10.0

**Comment by tsmethurst** [comment]
It's unlikely we would expose those APIs without authentication, since that would make it far easier for just anyone to come along and scrape those APIs. The client API of GtS is designed for authenticated client applications, not for callers who aren't clients to glean info about the instance and accounts on the instance. In that sense it's similar to Mastodon with secure mode enabled (I assume fedifetcher also doesn't work with secure mode mastodon, right?).

**Comment by ToadKing** [comment]
Understandable. While I can understand not wanting to scrape user statuses, I still personally see an advantage of opening up the status context API.

I guess unless this changes then FediFetcher can explicitly avoid trying to poll these APIs on GoToSocial servers.
