### ISSUE TITLE
How do I set up an account-domain when my domain is a CNAME to Vercel?

### ISSUE THREAD

**Issue by eallion** [superseriousbusiness/gotosocial#2054]
How do I set up an account domain when my domain xxx.com is a CNAME pointing to Vercel?

For example:

- host: m.xxx.com
- account-domain: xxx.com

But xxx.com is set up as a CNAME record pointing to Vercel. I can't set up a reverse proxy in this case.

**Comment by tsmethurst** [comment]
Mmm I think it's not really possible in cases where you have no control over the domain you're trying to set up as accountDomain.

**Comment by daenney** [comment]
You don't necessarily need a reverse proxy, but you need some type of functionality to redirect a few `/.well-known` endpoints from `xxx.com` to `m.xxx.com`.

Since you have `xxx.com` running on Vercel, I think the easiest way for you to go about this is by using [Vercel redirects](https://vercel.com/docs/concepts/edge-network/redirects).

**Comment by eallion** [comment]
Resolved. Use Next.js and Vercel Edge functions redirect.
