### ISSUE TITLE
[bug] Issues searching for accounts from multiple servers.

### ISSUE THREAD

**Issue by WesleyAC** [superseriousbusiness/gotosocial#2068]
### Describe the bug with a clear and concise description of what the bug is.

When searching for any account from the servers `mstdn.ca` or `spookygirl.boo` in Tusky, GTS shows no results

### What's your GoToSocial Version?

v0.10.0

### GoToSocial Arch

amd64 binary

### What happened?

I search for a user like `https://mstdn.ca/@announcements`, `@announcements@mstdn.ca`, `https://spookygirl.boo/@amy`, or `@amy@spookygirl.boo`, and I receive no results.

### What you expected to happen?

I see the searched user

### How to reproduce it?

Fairly standard GTS 0.10.0 instance, I haven't done any real tweaking of the config. I kinda assume this is a problem with my setup since I'm seeing this on multiple instances running different software, but maybe it's just a couple different bugs, idk.

### Anything else we need to know?

Logs:

```
Aug 03 20:33:16 interlace gotosocial[775303]: timestamp="03/08/2023 20:33:16.665" func=search.(*Processor).Get level=DEBUG maxID="" minID="" limit=20 offset=0 query=https://mstdn.ca/@announcements queryType=accounts resolve=true following=false requestID=f34hnfc904000q1ev39g msg="beginning search"
Aug 03 20:33:16 interlace gotosocial[775303]: timestamp="03/08/2023 20:33:16.666" func=middleware.Logger.func1.1 level=INFO latency=1.789248ms userAgent="Tusky/23.0 Android/12 OkHttp/4.11.0" method=GET statusCode=200 path=/api/v2/search clientIP=REDACTED requestID=f34hnfc904000q1ev39g msg="OK: wrote 59B"
```

I can't see anything obviously useful with trace log visibility and I don't know what I should redact from that, but let me know if you want me to try that.

**Comment by tsmethurst** [comment]
Hmm this sounds indeed like it could be a issue with your setup, I can deref those accounts OK from gts.superseriousbusiness.org which is running 0.10.0.

Probably a good idea to double check your reverse proxy settings (assuming you're running one) and, if relevant, any account-domain -> host forwarding you've got in place.

**Comment by tsmethurst** [comment]
Also, and this may sound silly, but when searching for accounts on Tusky make sure you're doing it from the 'accounts' tab on the search view, not posts or whatever.

**Comment by WesleyAC** [comment]
Also worth mentioning that I tried searching for posts from the users that I was interested in, which failed as well

**Comment by tsmethurst** [comment]
Hmmm. Can you verify that your domain name settings are correct in your dns provider for both ipv4 and ipv6? I've a feeling this might be related to that.

**Comment by WesleyAC** [comment]
I think IPv6 was configured right, but also am seeing some strange behavior, and my main internet isn't IPv6 capable right now so it's annoying to debug, so I removed the AAAA record and am seeing the same problem. I'll wait a bit to see if there are cache problems (although the TTL was pretty low, so it shouldn't be), but so far going v4 only doesn't seem to have fixed the problem.

**Comment by WesleyAC** [comment]
Checked again and I'm still seeing this problem after changing my DNS records to be IPv4 only

**Comment by mhitza** [comment]
I'm seeing similar issues on the instance I've started playing around with yesterday (config diff at the end of the message) .For example I can't follow the official account https://gts.superseriousbusiness.org/@gotosocial , wasn't able to lookup various accounts on various instances (for example `@mozilla@mozilla.social`), however I was able to trigger follows for others like: `@eff@mastodon.social` , and various `social.network.europa.eu` accounts (though still pending; maybe they need to accept my follow request?)

I'm running on the latest release 0.11.1, AAAA DNS record only, listening only on IPv6 interface, no reverse-proxy, deployed on RockyLinux 9.

Are there any flags or suggested settings that you'd like me to setup in order to further help debug this issue?

---

```diff
36c36
< log-client-ip: true
---
> log-client-ip: false
53c53
< host: "localhost"
---
> host: "third-party.cyou"
96c96
< bind-address: "0.0.0.0"
---
> bind-address: "[::]"
105c105
< port: 8080
---
> port: 443
125c125
< db-type: "postgres"
---
> db-type: "sqlite"
140c140
< db-address: ""
---
> db-address: "sqlite.db"
312c312
< instance-inject-mastodon-version: false
---
> instance-inject-mastodon-version: true
323c323
< accounts-registration-open: true
---
> accounts-registration-open: false
524c524
< letsencrypt-enabled: false
---
> letsencrypt-enabled: true
```

**Comment by tsmethurst** [comment]
@mhitza if you're listening *only* on IPv6 it may be that instances that don't (yet) use IPv6 might have trouble connecting to you. Do you also have an IPv4 address you could add to your dns records and listen on? If you do, and it works then, then it would help narrow things down.

**Comment by mhitza** [comment]
@tsmethurst it definitely seems to relate with the lack of an IPv4 address. After I've attached an A record to my domain to point at my server I was able to see the search results in Tusky for the above mentioned instances (eg. mozilla.social).

Following the logs, I see that the search process is a two-way process, ask target instance about a user, and remove target instance pings back my account.

When it works example (stripped timestamp+fluff from log) :

```
1 -> method=GET statusCode=200 path=/api/v2/search requestID=e1acmm4a04001spmprv0 msg="OK: wrote 59B"
2 -> method=GET url=https://mozilla.social/.well-known/webfinger?resource=acct%3Amozilla%40mozilla.social requestID=m5acmm4a04001aqsxwn0 pubKeyID=https://third-party.cyou/users/mhitza/main-key msg="performing request"
3 -> method=GET statusCode=200 path=/api/v2/search requestID=nxacmm4a04001mv3eykg msg="OK: wrote 59B"
4 -> method=GET url=https://mozilla.social/users/mozilla requestID=m5acmm4a04001aqsxwn0 pubKeyID=https://third-party.cyou/users/mhitza/main-key msg="performing request"
5 <- userAgent="http.rb/5.1.1 (Mastodon/4.1.4; +https://mozilla.social/)" method=GET statusCode=200 path=/users/mhitza/main-key requestID=v1ccmm4a0400159zmtkg msg="OK: wrote 558B"
6 -> method=GET url=https://mozilla.social/actor#main-key requestID=q5dcmm4a04000jacrgt0 pubKeyID=https://third-party.cyou/users/mhitza/main-key msg="performing request"
7 -> method=GET url=https://mozilla.social/actor requestID=q5dcmm4a04000jacrgt0 pubKeyID=https://third-party.cyou/users/mhitza/main-key msg="performing request"
```

When it doesn't (different user on mozilla.social):
```
1 -> method=GET statusCode=200 path=/api/v2/search requestID=802eam4a0400153p5jj0 msg="OK: wrote 59B"
2 -> method=GET url=https://mozilla.social/.well-known/webfinger?resource=acct%3AOscar%40mozilla.social requestID=dc2eam4a04001jtkvx50 pubKeyID=https://third-party.cyou/users/mhitza/main-key msg="performing request"
3 -> method=GET statusCode=200 path=/api/v2/search requestID=em2eam4a040008a7jbpg msg="OK: wrote 59B"
4 -> method=GET url=https://mozilla.social/users/Oscar requestID=dc2eam4a04001jtkvx50 pubKeyID=https://third-party.cyou/users/mhitza/main-key msg="performing request"
```

`1) + 2) + 3) + 4)` All happen between the time I hit search in Tuskey and the time results (or no results message) shows up
`5)` when it works it pings back for my user key
`6) + 7) + ...` further proceed with outgoing API calls

I assume the endpoints accessed at 2 and 4 do not provide the information necessary to display the user in search results?
Is there a timeout/wait mechanism within the code that waits for 5 to happen before it proceeds?
Is there a search endpoint message format to denote explicitly that something went wrong instead of returning no results because 5 didn't happen?

**Comment by NyaaaWhatsUpDoc** [comment]
@mhitza the process of checking the webfinger endpoint won't happen _every_ time, only if we haven't see that user before or our stored user hasn't been recently fetched from remote in a while. it uses that webfinger endpoint information to get a correct URI for then dereferencing the full user object (so request 4). While we're carrying out request 4, we receive request 5 as the remote server verifies our signed GET request we sent out in 4. The remote server will only allow complete their end of request 4 to complete once they have completed the handshake ongoing with 5.

In the case of the second user which failed the lookup, the request 4 will have returned a 404 (or some other 4xx) which is why the rest of the procedure won't have been carried out.

I think the solution here as you suggest, would be to make the error messages a little more transparent as to which stage of the process they failed.

**Comment by tsmethurst** [comment]
>  I couldn't lookup users on the https://gts.superseriousbusiness.org/ instance either. We're running the same software so there must be something IPv6 specific that's not handled quite right.

I just didn't get around to enabling ipv6 on that instance yet. Will have a crack at it this weekend if I get time.

On a software level, there's not really much to be done by us I think. GtS supports both ipv6 and ipv4, incoming and outgoing. Better logging of dns lookup failures would not be a bad idea, but that's informative and not really a bugfix per se.

I think in general it's more pragmatic to enable both ipv4 and ipv6 on your networking stack, instead of ipv6 only. There's a lot of lag in terms of folks enabling ipv6, for various reasons, so if you want optimum connectivity with other instances, better enable both.

**Comment by mhitza** [comment]
I think having a separate log entry when such circumstances arise would be helpful, and helpfuture users which will encounter this same issue. Eg. based on [my previous comment](https://github.com/superseriousbusiness/gotosocial/issues/2068#issuecomment-1702768341) log when step 5 doesn't take place? But that's my take, because now it's rather mysterious why this is happening.

Or change the config docs when listening on IPv6 to reference this issue.
