### ISSUE TITLE
[bug] Refused to load the image xxx because it violates the following Content Security Policy directive: "img-src 'self' blob:".

### ISSUE THREAD

**Issue by eallion** [superseriousbusiness/gotosocial#2126]
### Describe the bug with a clear and concise description of what the bug is.

Images referenced from my own image hosting service and SVG images embedded as data URIs both failed to display and showed errors:
```
Refused to load the image 'https://xxxxxxxxxx.com/piclist/202308090149737.webp' because it violates the following Content Security Policy directive: "img-src 'self' blob:".
```
![QQ截图20230817002035](https://github.com/superseriousbusiness/gotosocial/assets/1698841/6da8dda2-2374-4234-933f-6ea3173cc5d2)

### What's your GoToSocial Version?

v0.11.0

### GoToSocial Arch

amd64 Docker

### What happened?

When updating the version to v0.11.0, images started getting Content Security Policy errors.

**Comment by eallion** [comment]
Yes, those are all embedded images, hosted on my cloud bucket, no CORS. The svg for GoToSocial custom css.

**Comment by tsmethurst** [comment]
Alright thank you for confirming!

So, in the latest release we updated our HTML sanitization logic to disallow embedded `<img>` tags in posts, because for the most part they weren't federating properly to other instances, most other fedi softwares don't seem to support them, and they also are a vector for tracking pixels and things like that.

We plan to *probably* enable them again at some point once we figure out how to sanitize them properly, but for now they're turned off. So instead of using `<img>` links to share images, it's better to attach them to the post via the API so they're federated properly.

But anyway, the above doesn't really address the content-security-policy issue. For that, I think we will make a fix that allows people to specify additional sources for media in their configuration file, which will then be added to the content-security-policy for their instance. Would that work for you, for this use case?

**Comment by eallion** [comment]
Thanks for your reply!
Is there a way to post a picture without uploading it?

**Comment by tsmethurst** [comment]
> Is there a way to post a picture without uploading it?

Currently not, no. I guess you could just include a regular link to the image (not in an img tag), but that's just linking to a picture, so not really 'posting' it as such.

**Comment by eallion** [comment]
So I will keep using 0.10.0 until a new version that supports displaying images is released.

**Comment by eallion** [comment]
I would like to know, will this feat be restored in upcoming updates?

**Comment by daenney** [comment]
There's currently a snapshot build over at https://minio.s3.superseriousbusiness.org/browser/gotosocial-snapshots/MWUyZGI3YTMyZjcyZWUwMTQ5N2EwOGM2N2U2ZjdmNTA3ODkwZWU3MS8= that incorporates # #2134 with one more fix in the case of the S3 bucket URL not matching the public URL.

That should be all of it, so if you could try the snapshot build that would be great. There's now also an [`advanced-csp-extra-uris`](https://docs.gotosocial.org/en/latest/configuration/advanced/) that will work on the snapshot build so you can customise it further.

**Comment by eallion** [comment]
I like this project and I'm watching all activity in this repo. I pulled the snapshot docker images the first time, and that solved my initial issue. However, I have another question - I'm unable to post images using the `![]()` markdown syntax.

**Comment by tsmethurst** [comment]
Yeah that makes sense, that method of posting images is the thing that we disabled for now, for the reasons I gave earlier in the thread.

We *may* reimplement it later when we figure out how to do it properly, in a way that doesn't involve linking to external resources, and which doesn't risk federating tracking pixels. Until then, the supported way to attach images to a post is using the attachments API.

**Comment by tsmethurst** [comment]
Can I close this issue now, since the initial problem is resolved? I'll make another issue for inline images via `<img>`.

**Comment by eallion** [comment]
Thank you very much!

**Comment by tsmethurst** [comment]
No problem! :)
