### ISSUE TITLE
[question] clarification on issues with different fedi deployments per domain

### ISSUE THREAD

**Issue by corite** [superseriousbusiness/gotosocial#2168]
As you have explained in your [deployment documentation](https://github.com/superseriousbusiness/gotosocial/blob/2ec313a21fee25f5022e748315ea5e7d587384f6/docs/getting_started/index.md?plain=1#L41C2-L41C2) changing the fedi software you run on a specific domain may/will screw up federation. So far so good. 

My question now: is it problematic to have the same account domain here, or the same host? So, to put this into an example, if I first ran a mastodon instance with a configuration like:
```
host: "mastodon.example.org"
account-domain: "example.org"
```
and then a GoToSocial instance like this:
```
host: "gotosocial.example.org"
account-domain: "example.org"
```
will this still break federation, meaning the account-domains are actually the important part, or even both?

I understand that this is not really an issue with GoToSocial and rather with the Fediverse in general, but your documentation first made me aware of this issue and I was hoping that you would be able to clear that up :).

**Comment by tsmethurst** [comment]
Heya! So you definitely shouldn't use the same host because that will for sure break things.

But using the same account-domain *might* be OK, or it might still break things but in a slightly different way, especially if you re-use account names from the previous account-domain/host combination, since they might end up conflicting with stored accounts from the new account-domain/host combination.

So, not really recommended or supported. It *might* work, but it also might just break in deviously subtle ways that are difficult to debug + fix.
