### ISSUE TITLE
[bug] Some pngs give error `error decoding image: image: unknown format`

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2340]
### Describe the bug with a clear and concise description of what the bug is.

I was just looking at logs and:

```
timestamp="2023-11-07T04:43:39.068Z" func=dereferencing.(*deref).enrichAccount level=ERROR requestID=jzfhfa4b04000c030v60 msg="error fetching remote avatar for account https://social.handlerug.me/users/handlerug: fetchRemoteAccountAvatar: error loading attachment https://social.handlerug.me/fileserver/01QP5CG9VADMWT4Q08PW6CCYX3/attachment/original/01EANG35MK1P379GGQ8CA0XPJB.png: finish: error decoding image: image: unknown format"
```

Well… `file(1)` knows it as…

```
01EANG35MK1P379GGQ8CA0XPJB.png: PNG image data, 256 x 256, 8-bit/color RGB, non-interlaced
```

… and `xloadimage` displays it just fine.

### What's your GoToSocial Version?

0.12.1 git-5fdc005

### GoToSocial Arch

amd64 binary

**Comment by tsmethurst** [comment]
Ah interesting, yep I can replicate it on latest snapshot. Looks like an issue with the library we use for detecting file formats.

**Comment by tsmethurst** [comment]
Ah interesting, I tried downloading the image to my own computer from that instance, then uploading it as a media attachment on a locally-running GtS instance, and I get the same error...

**Comment by mirabilos** [comment]
tobi dixit:

>Ah interesting, I tried downloading the image to my own computer from
>that instance, then uploading it as a media attachment on a
>locally-running GtS instance, and I get the same error...

I also had a video today that wouldn’t show up but was viewable from
the remote instance; should I hunt that down so you have more examples
of misdetected media?

bye,
//mirabilos

**Comment by tsmethurst** [comment]
> I also had a video today that wouldn’t show up but was viewable from
the remote instance; should I hunt that down so you have more examples
of misdetected media?

No that's fine, thanks. We've already got a fix for that sort of issue in the works.

**Comment by tsmethurst** [comment]
Bit more of a writeup on this after looking at it a bit more:

The reason it returns `unknown format` error during `finish` is because it's trying to decode an image of 0 bytes.

In other words: the png was not stored, but nor did writing 0 bytes into storage return any errors.

I *think* the reason it's not being stored is because exif terminator is overzealously terminating the entire image as it's being streamed into storage. I'll have to do a bit more investigation of this to determine why that is the case. Doesn't make a lot of sense for it to do that, so I'm assuming it's a bug either in exif terminator, or in the png structure library that exif terminator depends on.

**Comment by tsmethurst** [comment]
https://github.com/superseriousbusiness/exif-terminator/issues/5
