### ISSUE TITLE
[bug] Timeout when trying to post

### ISSUE THREAD

**Issue by gaykitty** [superseriousbusiness/gotosocial#2471]
### Describe the bug with a clear and concise description of what the bug is.

Sometime when I try to post a status the operation times out and the post if never made. This has happened constantly for me recently in semaphore.social and only sometimes in Tusky. Whenever I try to post and it times out I get a lot messages like this:

```
Dec 18 06:51:27 turtle gotosocial[629853]: timestamp="18/12/2023 06:51:27.533" func=bundb.queryHook.AfterQuery level=WARN duration=3m0.223580574s query="INSERT INTO \"threads\" (\"id\") VALUES ('01HHYC321DJA6WE3ZD0MX7X82R')" requestID=5j4c2z4c04001n9c3s90 msg="SLOW DATABASE QUERY"
Dec 18 06:51:27 turtle gotosocial[629853]: timestamp="18/12/2023 06:51:27.533" func=server.glob..func1.Logger.func13.1 level=INFO latency=3m0.224395599s userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0" method=POST statusCode=499 path=/api/v1/statuses clientIP=<redacted> requestID=5j4c2z4c04001n9c3s90 msg="Client Closed Request: wrote 23B"
```

### What's your GoToSocial Version?

v0.13.0

### GoToSocial Arch

amd64 built from source via NixOS

### Other info

I am using a sqlite database.

**Comment by gaykitty** [comment]
Note as per #2422 I am running ANALYZE on a regular basis.

**Comment by tsmethurst** [comment]
This suggests to me that there's some underlying disk issue perhaps that's causing trouble. I recall from the other issue that you're using ZFS right? What kind of disks do you have backing up the filesystem?

**Comment by gaykitty** [comment]
Virtual block devices provided by Hetzer. SSD backed.

**Comment by tsmethurst** [comment]
Hmmm... do you have anything else using those drives? Any performance issues with other applications? To me a 3-minute long runtime for a very simple insert query suggests some kind of failure of the backing disks, but I'm not sure. I'm really not knowledgeable about ZFS unfortunately.

**Comment by NyaaaWhatsUpDoc** [comment]
Also useful, your configuration file (with parts you want censored doneso ofc) @gaykitty

**Comment by tsmethurst** [comment]
@NyaaaWhatsUpDoc Looks like the config is here :) https://github.com/superseriousbusiness/gotosocial/issues/2422#issuecomment-1845853994 Unless it's changed since then @gaykitty ?

**Comment by gaykitty** [comment]
It has not. Thx <3

**Comment by tsmethurst** [comment]
Probably also relevant / interesting:

https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Workload%20Tuning.html#sqlite
https://www.sqlite.org/pragma.html#pragma_page_size

So it could be a decent idea to try changing the SQLite page size, running `VACUUM`, and changing the ZFS record size.

Better check your disk integrity and all that jazz first though, just in case there's a degrading drive: https://www.reddit.com/r/hetzner/comments/rf938k/handling_your_first_dead_hard_drive_on_hetzner/

**Comment by gaykitty** [comment]
I have my zfs record size set to 4k, equal to the page size that was already set in sqlite. I have not done any vacuuming.

**Comment by mirabilos** [comment]
This possibly has two components.

One is the slow DB query / slow storage / etc.

The other is a thing I’ve seen happening when there are other reasons for the post to be slow: I was trying to upload a video with German internet, and GtS (proxied behind Apache httpd) closed the connection after 30 seconds, despite data still flowing in. (I’d have needed at least 1.5 Mbit/s upstream for it to complete in that time, and I think the WLAN is slow, too…)

Note that your Apache httpd, nginx, or whatever in front of GtS may also have timeouts and close the connection from their side if GtS takes too long to respond (slow DB/storage/…).

**Comment by gaykitty** [comment]
All storage devices (HDDS, SSD, etc.) for the most part are block storage devices and all databases operate on top of block storage ddevices.

**Comment by gaykitty** [comment]
You're also incorrect. A block storage device deals with blocks, not files. Filesystems are built on top of block storage. As for how well they deal with concerency, that tends to depend on the backing media.

**Comment by tsmethurst** [comment]
I meant hetzner block storage devices.

**Comment by gaykitty** [comment]
I admit I haven't tested it, but I doubt Heztner's SSD backed block storage is amazingly slow. If a GtS instance with a single medium sized account (124 follows, 170 follows), can't perform passably on pretty normal storage that's a problem imo. 

But I still think the problem is elsewhere. Are y'all having a lot of reports or poor performance? Are most users of my size not using sqlite? My server is not starved for rezources.

When I have time I'll do more debugging on my own. I'd ask that y'all either reopen this issue or provide another venue for me to document that process and solicet help when I do so.

**Comment by tsmethurst** [comment]
> I admit I haven't tested it, but I doubt Heztner's SSD backed block storage is amazingly slow. 

The reason I mention it is because from searching around a bit it seems there might be issues with storage speed:

- https://www.reddit.com/r/hetzner/comments/172ibpx/hetzner_cloud_volume_speed/
- https://gist.github.com/frozenice/fafb1565f8299a888f94d1113705de6c
- https://www.reddit.com/r/hetzner/comments/qyps0w/moving_database_storage_to_volumes/

Those are just reddit links and a gist, of course, so take them with a grain of salt, but the comment that Hetzner support does not guarantee speed of block storage had me wondering.

> Are y'all having a lot of reports or poor performance?

No, not really. Not recently at any rate, since we optimized a lot of the database queries over the last year. Certainly not reports about anything like 3-minute INSERT statements, that's just bananas.

Like I said somewhere else (in Matrix I think?) we're not doing anything unusual with SQLite that would warrant slowdown like that.

> Are most users of my size not using sqlite?

No idea. I'd assume a mix. I use SQLite on a 1-cpu, 1gb ram machine with ~300 followers/following and it's fine. The SQLite files are stored on the server's base volume, which is the same volume that GoToSocial is running from.

> I'd ask that y'all either reopen this issue or provide another venue for me to document that process and solicet help when I do so.

Feel free to reopen this issue if you can gather more clues about what the problem is, and it's something we can fix in GoToSocial.

One thing you might look at which I'm not sure has been mentioned yet, by the way, is reducing swappiness of your machine to 1. Having db caches put into swap is something that has bitten a few people in the ass with regard to GtS performance. Swappiness of 1 is usually recommended for database servers.

**Comment by gaykitty** [comment]
Damn. Didn't know Hetzer volume storage was that bad.

**Comment by gaykitty** [comment]
After moving my sqlite db off of volume storage and back onto my VPS's root drive, performance *seems* to be better. But it's only been a few hours.
