### ISSUE TITLE
[bug] Wrong error code for storage permission issue

### ISSUE THREAD

**Issue by Ryuno-Ki** [superseriousbusiness/gotosocial#2473]
### Describe the bug with a clear and concise description of what the bug is.

When I set up my GoToSocial (Bare Metal) I missed to update the configuration to point to the directory I want to store the images in. This led to a permission denied error ( https://github.com/superseriousbusiness/gotosocial/issues/2107 )

However, when submitting an avatar image of sufficient size, the UI reported a 400 Bad Request instead of a 500 Internal Server Error.

The issue is not with the payload of the request but with the server handling it. Therefore the status code is incorrect.

### What's your GoToSocial Version?

v0.13.0

### GoToSocial Arch

amd64

### What happened?

When I tried to set a sufficient small avatar image I received a 400 in the settings UI.
Looking into the server logs with Debug logging level I realised that I misconfigured my instance.

### What you expected to happen?

I was expecting a 500 response to help me look into the server logs earlier.

### How to reproduce it?

Configure GoToSocial with a storage path it has not permission to create. Then upload an image as avatar.

### Anything else we need to know?

I would understand if you close it as Won't Fix similar to https://github.com/superseriousbusiness/gotosocial/issues/2107
My argument here is to update the response code.

**Comment by daenney** [comment]
When GtS is running, we sort of assume that its dependencies function too. There's many reasons why even with correctly configured storage we may not be able to save the image (you ran out of space, the disk flips to read-only due to an issue etc.) There's no fool-proof way to detect this up front and in some cases the inability to store it can only be detected once we try to do an actual write to storage.

The way our handlers work is that we check a number of things in order and before we try to store it, including the size. When the image is too big, we'll never try to store it as you're violating a request constraint, so the 400 is correct regardless of whether the backing storage isn't functioning.
