### ISSUE TITLE
[feature] Allow non-breaking space to be used to create partial-word hashtags

### ISSUE THREAD

**Issue by mirabilos** [superseriousbusiness/gotosocial#2489]
### Describe the bug with a clear and concise description of what the bug is.

I just posted something with `#ferrophil|e`, which is a “standard” way to say “make `#ferrophil` a hashtag, then append the `e` but don’t make it part of the hashtag, which I’ve often seen used. (The `|` is usually retained, even if it would be nicer without.)

However, this made GtS fail to recognise it as a hashtag at all, posting it as plaintext instead.

### What's your GoToSocial Version?

0.13.0-rc2 git-d0bb8f0

### GoToSocial Arch

amd64 binary

### Anything else we need to know?

This has “cosmetic” priority, i.e. don’t bother much on my account, or use it as newcomer onboarding issue or something.

**Comment by tsmethurst** [comment]
> a “standard” way

Hmm, standard in what sense? As in, this is a workaround that works on Mastodon or so?

Does it work with zero-width spaces, just out of interest?

**Comment by mirabilos** [comment]
> Hmm, standard in what sense? As in, this is a workaround that works on Mastodon or so?

I’ve seen that in use on Fedi, on Twitter, and probably elsewhere as well, and I’ve never seen people use anything else, so “industry standard”?

> Does it work with zero-width spaces, just out of interest?

All of ZWNBS (U+FEFF), ZWNJ (U+200C), ZWJ (U+200D), ZWS (U+200B) also prevent the hashtag from forming at all.

These are also harder for ordinary people to type, I suppose ☻

**Comment by tsmethurst** [comment]
Hey did you try this with a backslash btw? curious if that would work

**Comment by tsmethurst** [comment]
I'll close this since there's a workaround; there's no real "standard" for how hashtags should be separated, and tbh I don't think there really needs to be either.

**Comment by xabirequejo** [comment]
In Basque we decline nouns, and we use zero width spaces since 2015 to separate the root from the declension mark (nominative, genitive, dative, accusative, ablative…).

The word (or words) can be read properly but the hashtag is only applied to part of the word. I'm **#testi**ng #GoToSocial. 

Both Twitter and Mastodon work as expected (we use this [browser extension](https://github.com/iametza/datraolat) or long press D on AnySoftKeyboard), but I haven't been able to use ZWS successfully with GtS.

Phanpy doesn't seem to recognise the space and therefor the hashtag is applied to the whole word, whereas inserting the ZWS on Elk and Tuba renders the hashtag useless:
<img width="661" alt="Screenshot showing GtS messages sent via Phanpy, Elk and Tuba." src="https://github.com/user-attachments/assets/7fd194cb-ad3e-4fe8-9709-55f68e29b980">

Screenshot of Mastodon, where the ZWS separate the root from the -n declension mark.
<img width="392" alt="Screenshot of a message sent via Mastodon UI" src="https://github.com/user-attachments/assets/7be51819-6662-4707-b3fa-39e214632910">

I'm not sure this is related to GtS itself or the clients.
If this is related to the server and not the clients, I'd like GtS to reconsider reopening this issue so that also non-English speakers can make the most out of social media without giving up on our mother tongue.

**Comment by tsmethurst** [comment]
I'll reopen this as a feature request to treat non-breaking space the same as space when parsing hashtags :+1:

**Comment by xabirequejo** [comment]
Thank you very much
