### ISSUE TITLE
Looking for Documentation on "gotosocial" Database Structure

### ISSUE THREAD

**Issue by huabin** [superseriousbusiness/gotosocial#2504]
Hello everyone!

I'm currently working on a project that requires a detailed understanding of the "gotosocial" database structure and organization. I've attempted to find official documentation or any related resources, but unfortunately, I haven't come across any documentation regarding its structure.

If anyone is familiar with the "gotosocial" database structure or knows of documentation outlining its tables, relationships, and other essential components, I would greatly appreciate it if you could share.

If you have any information or suggestions, I would be immensely grateful for your assistance. Thank you all for your help!

**Comment by tsmethurst** [comment]
We haven't documented the database structure yet because tables and columns and indexes and whatnot are constantly changing during the alpha phase of development. Looking through the tag annotations on the models in `internal/gtsmodel` should give you a solid indication of how everything works though.

**Comment by tsmethurst** [comment]
What are you working on btw?

**Comment by huabin** [comment]
@tsmethurst Thanks for the reply. I am learning to create an application for the Fediverse, and gotosocial is a good example for learning.
