### ISSUE TITLE
[feature] oidc force to use preferred_username (or cancel) during inital login

### ISSUE THREAD

**Issue by wrenix** [superseriousbusiness/gotosocial#2617]
### Is your feature request related to a problem ?

I do not like, that somebody rename during first login his `preferred_username` (from oidc given) to an name like maybe somebody other has / use.

### Describe the solution you'd like.

i configuration option to skip the initial creation request if the username is correct.

### Describe alternatives you've considered.

NONE

### Additional context.

scenario:
  - i nickname `wrenix` has the `preferred_username: me` on my oidc-provider
  - i login with oidc, i get `me@example.org`
  - i create an other "random" user on my oidc-provider with `preferred_username: friend`
  - he logins and during inital gotosocial login he rename `friend@example.org` to `wrenix@example.org`
  
everybody thing, my friend is me now (because we has change his name that way).

**Comment by wrenix** [comment]
@tsmethurst have your seen this? (maybe this issues was overseen, i created multiple issues at the same time)

**Comment by daenney** [comment]
I'm going to close this for now. As Tobi mentioned, we're not targetting environments where this is a concern. This is also something that can be solved by an admin and you can kick people that are misbehaving out of your auth provider and from your instance.

**Comment by wrenix** [comment]
I understand, that it has no priority, because you want to focus to support small setups. But a lot of small organisations has an IdP, so i believe that everybody with an IdP need that option.

So please keep it in the backlog.

**Comment by daenney** [comment]
Given GtS has supported external authentication providers for a long time and it's not otherwise come up as an issue. That makes the argument that "everyone needs this" neitheer compelling nor convincing. Just because something is important to you doesn't create an obligation on GtS to implement it or for us to keep it in the backlog. There's no use to a backlog full of things we don't feel fit with the project's goals.

Not every social issue needs a technological solution. Whether you're a small or a big organisation and whether you have an IdP or not, you already have the ability to address people hijacking usernames (that aren't in use yet). Talk to them.
