### ISSUE TITLE
[feature] Hot reload config on `SIGHUP`

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#270]
For better daemonization, we should allow the GoToSocial binary to respond properly to `SIGHUP` events by reloading configuration either from file or environment variables.

This will take a bit of work because currently the config paradigm is just 'load everything at the beginning, pass a pointer to the config around, only read from config'. We'll probably have to mutex the config so that we can lock it while writing, and also find any cases where we initialize a struct by taking some value from the config but not the config itself, and make sure those get reloaded as well.

**Comment by tsmethurst** [comment]
Relates to https://github.com/superseriousbusiness/gotosocial/issues/269

**Comment by igalic** [comment]
I don't know if config includes LetsEncryptCertificates, but these also need to be considered.
(or not, when the option is disabled)

**Comment by daenney** [comment]
I would suggest we don't do this. Life is much simpler if we can assume that once processed, configuration remains the same for the lifetime of the process. Ensuring that configuration changes propagate correctly across the code base would require us tearing down and restarting the processors, DB connections and HTTP handlers. At that point, we've essentially reached the equivalent of restarting the process, minus the actual replacing the process part.

GoToSocial configuration is in general not something that people tweak on the regular. I doubt that in practice people end up restarting GtS due to a configuration change more than 2-3 times a year. The most likely time people may need to restart GtS for a configuration change is when upgrading to a new release, but that's unavoidable.

**Comment by tsmethurst** [comment]
I agree :) Gonna close this!
