### ISSUE TITLE
[bug] Streaming api URI is a bit different from Mastodon

### ISSUE THREAD

**Issue by urmaul** [superseriousbusiness/gotosocial#2704]
### Describe the bug with a clear and concise description of what the bug is.

WebSocker connection request to `/api/v1/streaming/?stream=user&access_token=XXX` returns "301 Moved Permanently".

### What's your GoToSocial Version?

v0.13.3

### GoToSocial Arch

Docker

### What happened?

I tried to connect to my GoToSocial instance using https://github.com/h3poteto/megalodon and telling it the server is Mastodon.

Normal API calls succeed but streaming connection fails with unexpected "301 Moved Permanently" with redirection from  `/api/v1/streaming/?stream=user&access_token=XXX` to  `/api/v1/streaming?stream=user&access_token=XXX` (note the missing trailing slash).

### What you expected to happen?

Streaming connection works without errors.

### How to reproduce it?

Try to open stream while using megalodon as a client.

Or call `/api/v1/streaming/?stream=user&access_token=XXX`.

### Anything else we need to know?

Hacking into the megalodon source code and removing a slash there fixes the issue. In this case streaming works as expected.

At the same time my client was trying to make streaming connection to an instance with Mastodon `v4.3.0-nightly.2024-02-22+glitch`. It worked well in both cases: with the trailing slash and without it. Could GoToSocial also support both options?

Theoretically, we can fix it in megalodon by adjusting the URI or allowing redirects but there are many clients around and they all can have the same issue.

**Comment by tsmethurst** [comment]
Hmm, Mastodon might accept both formats, but in this case the API docs are pretty clear about what the URL for websockets streaming is (ie., without the trailing slash): https://docs.joinmastodon.org/methods/streaming/#websocket

Due to the router engine we use and the way it matches URLs, this is not trivial to fix on GtS's side, so I'd suggest that it would be better to fix it in the megalodon library instead.

Worth noting that `/api/v1/streaming` and `/api/v1/streaming/` are actually semantically different URLs. Typically path with a trailing slash would indicate a directory, but GtS redirects from trailing slash endpoints to their non-trailing equivalents because it doesn't service directories via the router.
