### ISSUE TITLE
[bug] URLs with non-ascii chars not detected properly when parsing a new status

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#2755]
When composing a post, only fully ascii URLs are picked up properly as links, URLs with non-ascii utf-8 characters in are split after the first character.

For example: `https://example.org/söme_url` is rendered as `<a href="https://example.org/s" rel="nofollow noopener" target="_blank" title="https://example.org/s">https://example.org/s</a>öme_url`

We oughta see if we can fix this, I believe it's something in goldmark we need to configure/change (`internal/text`).

**Comment by daenney** [comment]
I think convention dictates those ought to be sent/received %-encoded, and then user agents can decide to show them as their unicode equivalent (browsers do this for example). That would avoid the issue. But if it's actually coming in as such then we'll have to deal with it I suppose.

**Comment by NyaaaWhatsUpDoc** [comment]
since it's incoming as part of status content, and not a uri being passed as some AP property value (e.g. actor), i think we should support it. otherwise yeah i'd say these absolutely must be % encoded.

other than being plaintext or marked up specifically with markdown, the status content shouldn't need to pre-percent-encode their urls imo, that should be on us when we create HTML form of it
