### ISSUE TITLE
[question] how do i make servers that federated with mine know that i've deleted the server?

### ISSUE THREAD

**Issue by millionsofplayers** [superseriousbusiness/gotosocial#2771]
i ran a test gotosocial server on a vps for like a day and i forgot to let the instances that federated with it in that time know that it was going to be deleted.

Fast forward a month and i've set up cloudflare on my home server. I check what requests i'm getting and i see i'm getting webfinger and other fediverse requests from random instances, who probably think i'm still hosting something there.

I don't have access to the vps anymore, how do i stop the instances from sending requests to my server?

**Comment by rdelaage** [comment]
This was the case of the `queer.af` mastodon instance. They sent delete activities for all accounts to all known instances. If you have a backup of your instance, you could try something like this. Otherwise, this is difficult on the fediverse to delete something.

**Comment by tsmethurst** [comment]
Hmm indeed, unfortunately if the server has already been deleted and you don't have a backup to send Delete activities from, there's not much that can be done. Remotes will just assume that the accounts on your instance are still there. One thing you could do (but it's a pain...) is check the user-agents of incoming requests to see which fedi instances are sending things to you still, and contact the admins of those instances and ask them to defederate from your domain.

In future we'll implement #1697 so that admins can send out Deletes more easily before bringing an instance down.

**Comment by millionsofplayers** [comment]
i think all i did on the instance was make an account, change some info on it, send a few posts then delete it

i don't have a backup

**Comment by millionsofplayers** [comment]
I noticed that a lot of servers (mainly mastodon social) are POST requesting /users/millions/inbox HTTP/1.1 so I used a cloudflare firewall rule to block requests to that path unless localhost is doing it, hopefully that works since I can’t ask servers to delete the info automatically

**Comment by tsmethurst** [comment]
That seems fine. When accounts and stuff get deleted, mastodon tends to send out a lot of delete messages to every single known server, even if you never followed or even saw the account in question. Blocking inbox POSTs is a reasonable way of dealing with that unwanted traffic imo. If it's alright with you, I'll close this issue now since you've put a workaround in place.

**Comment by millionsofplayers** [comment]
Sure
