### ISSUE TITLE
[feature] option to make follow and/or follower list not public

### ISSUE THREAD

**Issue by selfisekai** [superseriousbusiness/gotosocial#2772]
### Is your feature request related to a problem ?

publicly available follow relations can be used for targeting harassment

### Describe the solution you'd like.

option for a user to disable (return empty list?) endpoints on their account for any other or unauthenticated users (and also instance admins?):
- `/api/v1/accounts/:id/followers`
- `/api/v1/accounts/:id/follows`
- `/users/:id/followers`
- `/users/:id/follows`
- (anything missing?)

### Describe alternatives you've considered.

none

### Additional context.

Mastodon has a checkbox in `/settings/privacy` that can be disabled: "Show follows and followers on profile. People will be able to browse through your follows and followers. People that you follow will see that you follow them regardless." (API equivalent: [`PATCH /api/v1/accounts/update_credentials`](https://docs.joinmastodon.org/methods/accounts/#update_credentials) - `hide_collections=true`.

Akkoma (Pleroma?) has an equivalent, but splits that into `hide_followers` and `hide_follows` separately, and also adds `hide_followers_count` and `hide_follows_count`, which additionally turn off the counters visible on the profile.

<details>
<summary>side note</summary>
i wish you, reader, not having anything like this in your threat model.
</details>

**Comment by tsmethurst** [comment]
Good one! I thought we had an issue open for this already but we apparently don't.

We already don't allow unauthenticated users to access the client API, so only people you share an instance with will be able to see your followers/following via that method. We also don't show them via the web view. Since GtS has so far primarily been for single-user or very small instances (ie., with people you know personally), that's why this hasn't been a priority yet.

However we do serve followers/following as activitypub collections on the AP model of an account so we'll have to make sure we change that too when implementing this.

I think this is not a big change, so we can probably include these things in 0.15.0. Thanks for opening.

**Comment by selfisekai** [comment]
hm. i've deployed this in my nginx config for now:
```nginx
location ~* ^/users/[^/]+/follow(?:er)?s {
    return 501;
}
```
