### ISSUE TITLE
[bug] Cannot federate with Mastodon's Authorized Fetch

### ISSUE THREAD

**Issue by islekcaganmert** [superseriousbusiness/gotosocial#2814]
### Describe the bug with a clear and concise description of what the bug is.

Mastodon has a feature called [authorized fetch](https://fedi.tips/authorized-fetch/) that forces other systems to grab an auth key to federate. Since [Mastodon is 72.8% of fediverse](https://fedidb.org/), most others are also supporting. I believe this is only possible description of why gotosocial is unable to federate with Threads and instances that has this enabled.

### What's your GoToSocial Version?

0.14.2+git-0bd95d7

### GoToSocial Arch

amd64

### What happened?

Unable to view actors from Authorized Fetch enabled instances.

### What you expected to happen?

What is expected is to view these as any other.

### How to reproduce it?

1. Setup a new server
2. Create an account and set everything public
3. Login via any Mastodon client
4. Search for an actor from Authorized Fetch enabled instance

### Anything else we need to know?

As ActivityPub develops, Authorized Fetch becoming more common. gotosocial needs it as there is not any other choice which is that lightweight.

Also it shows that this external instance I am trying to connect to is making request to my main-key when I tried to fetch.

**Comment by NyaaaWhatsUpDoc** [comment]
gotosocial has had authorized fetch since the beginning. you clearly have done next to no research here. gotosocial federates with authorized fetch mastodon, akkoma etc instances with no issues. if you have a specific bug related to federation with those servers you're free to raise it!

but we are absolutely not interested in going out of our way to be compatible with Threads. Meta are morally, fucking bankrupt.

**Comment by islekcaganmert** [comment]
> gotosocial has had authorized fetch since the beginning. you clearly have done next to no research here. gotosocial federates with authorized fetch mastodon, akkoma etc instances with no issues. if you have a specific bug related to federation with those servers you're free to raise it!

I have debugged the code and logs . Both suggests authorized fetch is clearly misbehaving. I know gotosocial implemented something for this, this is why I added it as a bug, not feature request.

> but we are absolutely not interested in going out of our way to be compatible with Threads. Meta are morally, fucking bankrupt.

Your documents says that the reason why there is not any flagship server is that you do not want to do the moderation and you are currently saying that you are not interested in with nature of ActivityPub. Is it your principle to use your work to force your ideological ideas to users? Maybe I should check to source code for any kind of server blocking...

**Comment by NyaaaWhatsUpDoc** [comment]
if talk of not wanting to work with [genocide enablers](https://www.amnesty.org/en/latest/news/2022/09/myanmar-facebooks-systems-promoted-violence-against-rohingya-meta-owes-reparations-new-report/) like Meta makes you worried that we're pushing an "idealogy", you're not someone we want contributing to the project.

**Comment by tsmethurst** [comment]
Closed this since it's going nowhere fast.

As @NyaaaWhatsUpDoc mentioned, we've been federating successfully with authorized fetch instances for years now, and have put extensive work into debugging possible issues over those years. Our support for authorized fetch is documented here: https://docs.gotosocial.org/en/latest/federation/federating_with_gotosocial/#http-signatures and it's also mentioned in our readme here: https://github.com/superseriousbusiness/gotosocial/?tab=readme-ov-file#safety--security-features

As for threads, we've had an issue open for that here, which we've since closed as federation issues look like a bug on their side: https://github.com/superseriousbusiness/gotosocial/issues/2491
