### ISSUE TITLE
[bug] Trunks can't follow accounts (sends json boolean as string)

### ISSUE THREAD

**Issue by justdaj** [superseriousbusiness/gotosocial#3010]
### Describe the bug with a clear and concise description of what the bug is.

using https://trunks.social, I am unable to follow any accounts ( Local or Remote accounts)

Clicking the follow button does nothing on the UI

### What's your GoToSocial Version?

V0.16.0-rc3

### GoToSocial Arch

arm64 Binary

### What happened?

Nothing.  No error message to the user.  The Button does not change  to unfollow.

Looking at the browser console, the click generates an error:

`Failed to load resource: the server responded with a status of 400 (Bad Request)`

### What you expected to happen?

A follow request is successful

### How to reproduce it?

- Within Trunks, search for a user 
- Open the profile
- Click the Follow button on the bottom right of the screen

**Comment by tsmethurst** [comment]
Hiya, in the browser network tab could you check the content of the network request to see what trunks is submitting to the gts api? And also check what gts is returning as an error message? That should give more info about what trunks is doing that GtS doesn't like.

**Comment by justdaj** [comment]
Sure.  See below.

I don't use Trunks generally -- it's a nice interface but it has no spell-checking feature, which means I produce some amazing typos!  

I thought it would be good to test a few of the popular PWAs

## Request

```
Request URL:
https://cctb.social/api/v1/accounts/01HZZ9761BXCZPCAS7YE9VN0P8/follow
Request Method:
POST
Status Code:
400 Bad Request
Remote Address:
95.216.196.128:443
Referrer Policy:
strict-origin-when-cross-origin
```

### And the response

```
{
    "error": "Bad Request: json: cannot unmarshal string into Go struct field AccountFollowRequest.reblogs of type bool"
}
```

## Another Network request

```
Request URL:
https://cctb.social/api/v1/accounts/01HZZ9761BXCZPCAS7YE9VN0P8/follow
Request Method:
OPTIONS
Status Code:
204 No Content
Remote Address:
95.216.196.128:443
Referrer Policy:
strict-origin-when-cross-origin
```

### Response

No response

**Comment by tsmethurst** [comment]
Right, it looks like it's providing some boolean fields as a string like this: `{"some_field": "true"}` but it should be doing them like this: `{"some_field": true}`. We've seen something like this before. It only works because Mastodon (ie., Ruby on Rails) coerces that into a boolean, but the API docs specify it should be a boolean (https://docs.joinmastodon.org/methods/accounts/#form-data-parameters-2). So this is something Trunks should probably change on their side.

**Comment by daenney** [comment]
It's form data and form data has no boolean type. Same with URL params. Everything is a string. So whether we get `false` or `"false"`, we should interpret both as strings and coerce them to boolean if we happen to know that that field is intended to be interpreted as a boolean. Most implementations will simply not quote a boolean when emitting it so it probably works accidentally 95% of the time.

We could ask Trunks to fix it since every other client seems to be fine so far, but we may want to consider coercing boolean form data/URL params correctly ourselves.

**Comment by daenney** [comment]
Just to be clear, I don't believe it's sending JSON bools as string. You don't submit JSON on that endpoint, it's forms.

**Comment by daenney** [comment]
Or hmm, maybe it does. We accept a bunch of encodings and our form attribute mapper should already be handling this correctly. Mildly annoying that their source code isn't open source.

**Comment by tsmethurst** [comment]
It's definitely using the JSON decoder, if you look at the response: `json: cannot unmarshal string [...]`. For form-data we do already coerce these things properly I believe (since as you say form-data stuff is all strings).

**Comment by daenney** [comment]
Ah yeap, you're right. Then that needs fixing on Trunk's side. Booleans in JSON have their own type, we don't wrap quotes around that.

They do have a public issue tracker on GitHub, so I can file an issue there. I'll close this one afterwards.

**Comment by Fastidious** [comment]
@daenney did you end up filling an issue for this on `trunks-public`? Could you share the ID? Thanks!

**Comment by daenney** [comment]
It's trunks-social/trunks-public#310. The encoding of booleans as strings in JSON is something we consider a client bug and one that seems unique to Trunks. This is not something we'll fix on the GtS side by adding some form of type coercion to the client API.

As such, I'm going to close this on our side.
