### ISSUE TITLE
[bug] PopulateAccount: error populating account settings: SQL logic error: no such table: account_settings 

### ISSUE THREAD

**Issue by aklsh** [superseriousbusiness/gotosocial#3012]
### Describe the bug with a clear and concise description of what the bug is.

The web frontend is just blank. I also cannot fetch any posts in any clients. Older posts are also not seen.

Seeing this in the logs when I tried to update from v0.14.2 to 0.16.0... I also saw that it broke in v0.15.0 as well, so I guess something that in that broke it in this way. Might be https://github.com/superseriousbusiness/gotosocial/pull/2770 (basing this on it being the only search result for `account_settings` in Issues/PRs).

```
timestamp="16/06/2024 14:41:59.484" func=typeutils.(*Converter).accountToAPIAccountPublic level=ERROR requestID=q1t7y8cg04001w5cxav0 msg="error(s) populating account, will continue: PopulateAccount: error populating account settings: SQL logic error: no such table: account_settings (1) (code=1)"

timestamp="16/06/2024 14:41:59.484" func=server.init.func1.Logger.14.1 level=ERROR stacktrace="()\n\t/usr/local/go/src/runtime/panic.go:261\nruntime.sigpanic()\n\t/usr/local/go/src/runtime/signal_unix.go:881\ntypeutils.(*Converter).accountToAPIAccountPublic()\n\t/drone/src/internal/typeutils/internaltofrontend.go:278\ntypeutils.(*Converter).AccountToAPIAccountPublic()\n\t/drone/src/internal/typeutils/internaltofrontend.go:150\ntypeutils.(*Converter).InstanceToAPIV1Instance()\n\t/drone/src/internal/typeutils/internaltofrontend.go:1421\nprocessing.(*Processor).InstanceGetV1()\n\t/drone/src/internal/processing/instance.go:42\nweb.(*Module).indexHandler()\n\t/drone/src/internal/web/index.go:33\ngin.(*Context).Next()\n\t/drone/src/vendor/github.com/gin-gonic/gin/context.go:185\nserver.init.func1.Logger.14()\n\t/drone/src/internal/middleware/logger.go:134\n" requestID=q1t7y8cg04001w5cxav0 msg="recovered panic: runtime error: invalid memory address or nil pointer dereference"

timestamp="16/06/2024 14:41:59.484" func=server.init.func1.Logger.14.1 level=INFO latency="4.411539ms" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0" method=GET statusCode=200 path=/ clientIP=172.24.0.3 errors="Error #01: recovered panic: runtime error: invalid memory address or nil pointer dereference\n" requestID=q1t7y8cg04001w5cxav0 msg="OK: wrote 16.0EiB"

timestamp="16/06/2024 14:41:59.734" func=server.init.func1.Logger.14.1 level=INFO latency="57.631µs" userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0" method=GET statusCode=404 path=/favicon.ico clientIP=172.24.0.3 errors="Error #01: Not Found\n" requestID=pstqy8cg0400197zexxg msg="Not Found: wrote 21B"
```

### What's your GoToSocial Version?

v0.16.0

### GoToSocial Arch

amd64 Docker

**Comment by tsmethurst** [comment]
Sounds like a database migration was interrupted and so the account settings table was not created. Would be a good idea to restore to a db backup of your previous version before the update and run the update again.

**Comment by rsolvang** [comment]
@aklsh I have the exact same problem!

Tried to upgrade from 0.14.2 to 0.15.0, but it gts did not start. I let it run for a while since it was a database migration on this upgrade, but nothing. So I downgraded and waited for 0.16.0. When I tried 0.16.0 now, I got the same error as you did: `error executing command: error creating dbservice: db migration error: SQL logic error: no such table: account_settings (1) (code=1)`

**Comment by tsmethurst** [comment]
> but nothing

What do you mean? You mean it didn't start? Or you canceled out after some amount of time? Just checking.

**Comment by aklsh** [comment]
> What do you mean? You mean it didn't start ever? Or you canceled out after some amount of time? Just checking.

I have watchtower automatically updating the gotosocial container to the latest version, so it was a while (many hours) before I noticed that gotosocial didn't start.

**Comment by tsmethurst** [comment]
Thanks for the extra detail. I think there's not much you can do in this case apart from try the update again from a restored backup of your database from 0.14.2 or 0.15.0. We don't support rolling *back* versions at this point (eg., running GoToSocial 0.15.0 from a database that's already had its schemas updated to those of 0.16.0), so it's possible that that also contributed to the issue, but I'm not sure.

Just for the record, we've only ever seen issues like this when the migration has been interrupted prematurely, so you may want to double check your setups to make sure that something like a health check isn't killing + restarting the service while it's in the middle of migration, since health check endpoints aren't available while the database is being churned through + reindexed.

In future we may add code to try to re-run migrations for cases where something has gone wrong, but that hasn't been a priority for alpha since the migration code has been pretty reliable.

Ps., If you don't have backups and you do want to try manually creating tables and indexes and stuff, you could look at the migrations here: https://github.com/superseriousbusiness/gotosocial/tree/main/internal/db/bundb/migrations, but please note that this is totally unsupported.

**Comment by tsmethurst** [comment]
Yes, you could try doing that using the import/export CLI :) https://docs.gotosocial.org/en/latest/admin/cli/#gotosocial-admin-export

If you wanna go down that route, export using 0.14.2 (or whatever version was last working for you), import into a fresh db using 0.14.2, run first for a bit to make sure stuff works, and *then* try upstepping to 0.16.0. Don't export using 0.14.2 and import using 0.16.0, because it won't recognize the format. Whatever you do, make db backups before + after.

Just be aware when you do an export/import cycle it keeps only the bare minimum stuff it needs to keep federation working; it preservers follows/followers etc, but you'll lose your statuses and media.
