### ISSUE TITLE
[bug] searching for url containing german umlaut

### ISSUE THREAD

**Issue by chri2** [superseriousbusiness/gotosocial#3063]
### Describe the bug with a clear and concise description of what the bug is.

```
$ curl -X GET --header 'Authorization: Bearer TOKEN' 'http://127.0.0.1:25447/api/v1/search?resolve=true&q=https%3A%2F%2Frelay.fedi.buzz%2Ftag%2Ftr%C3%B6%C3%B6t'
{"error":"Internal Server Error"}
```

This searches for the URL `https://relay.fedi.buzz/tag/tr%C3%B6%C3%B6t` like shown on https://relay.fedi.buzz/ and should return the account `@tag-troot@relay.fedi.buzz` . 

server log message:
```
timestamp="03/07/2024 09:26:07.230" func=httpclient.(*Client).DoOnce level=INFO method=GET url=https://relay.fedi.buzz/.well-known/webfinger?resource=acct%3Atag-troot%40relay.fedi.buzz attempt=0 requestID=j617rxwg040001c0368g pubKeyID=https://hallo.ween.de/users/nachrichten/main-key msg="200 OK"
timestamp="03/07/2024 09:26:07.231" func=server.init.func1.Logger.14.1 level=ERROR latency="237.907794ms" userAgent=curl/7.74.0 method=GET statusCode=500 path=/api/v1/search clientIP=127.0.0.1 errors="Error #01: Get: error searching by URI: byURI: error looking up https://relay.fedi.buzz/tag/tr%C3%B6%C3%B6t as account: enrichAccount: dereferenced account uri https://relay.fedi.buzz/tag/troot does not match https://relay.fedi.buzz/tag/tr%C3%B6%C3%B6t\n" requestID=j617rxwg040001c0368g msg="Internal Server Error: wrote 33B"
```

Replacing `trööt` by `test` works and returns the expected result.

### What's your GoToSocial Version?

0.16.0+git-f1cbf6f

### GoToSocial Arch

arm64

### Anything else we need to know?

Thanks for the great software and the good vibes in the community!

**Comment by tsmethurst** [comment]
Thanks, I'll see if I can reproduce. I know searching for other accounts with characters outside the silly limited ascii set works fine because I've done it before, so perhaps there's a regression or a bug specific to fedi buzz.

**Comment by VyrCossont** [comment]
This seems like a relay.fedi.buzz bug, or at least quirk. Creating an actor from a tag name applies [`deunicode`](https://github.com/kornelski/deunicode) normalization to the tag name https://github.com/astro/buzzrelay/blob/997471d/src/actor.rs#L18 which is then served as the actor ID, which means an actor URL that contains an umlaut will always be served with an actor ID without an umlaut.

GtS expects the returned actor ID to match the one we searched for. Mastodon apparently doesn't care; I was able to resolve the umlauted tag actor on the current mastodon.social version (4.3-nightly) to the non-umlauted version. [AP is predictably vague on whether resolving an URL to an actor needs to result in an actor that has that URL as its ID,](https://www.w3.org/TR/activitypub/#actors) so I'm not sure which behavior is more correct.

**Comment by tsmethurst** [comment]
It's sorta unfortunate imo that `trööt` and `troot` are treated as the same word in mastodon, as they're actually not the same word at all, but there's nothing we can do about that. I think in this case it's probably something that fedi buzz can fix by recommending the "normalized" (deunicoded) version to users looking for tags, ie., `https://relay.fedi.buzz/tag/troot` instead of `https://relay.fedi.buzz/tag/trööt`.

On our end, we support searching for URLs that contain characters outside the ASCII range, so there's nothing to do in that regard; and imo it's correct that we should reject an Actor if the final URL it was served from doesn't match the ActivityPub ID that was used to search for it, as a really basic security measure. I think in Mastodon's case they just check that something is on the same domain, not the exact same URI, but I'm wary that that may still leave some vulnerabilities that I'd rather not risk.

So I'm going to close this from our side. @chri2 could you follow https://github.com/astro/buzzrelay/issues/19 for further work on this issue?

**Comment by chri2** [comment]
Yes, please, closed and **thanks** for investigating! Subscribed to the buzzrelay issue.

One thing: as I (and maybe others) do recommend the service to other GTS admins it might be worth putting some information about this case into an FAQ?
