### ISSUE TITLE
[feature] Add option to hide even "public" posts from web view of profile

### ISSUE THREAD

**Issue by lilithserenada** [superseriousbusiness/gotosocial#3249]
### Is your feature request related to a problem ?

I would prefer my instance not to be viewed by non-ActivityPub users to cut down on this trivial form of block evasion and anonymous monitoring.

### Describe the solution you'd like.

Make DISALLOW_UNAUTHENTICATED_API_ACCESS available via config.yaml

### Describe alternatives you've considered.

I noticed that GoToSocial defaults to Unlisted visibility, and through an opt-in mindset on a global network this is awesome! A limiting factor of this is that only my Followers (and theirs, if they repost) can see my posts. I would like my posts to be able to take advantage of built-in network discovery tools only within my block/allowlist specifications. I believe adding functionality for DISALLOW_UNAUTHENTICATED_API_ACCESS will enable this.

**Comment by tsmethurst** [comment]
I'm not really sure what you're asking for here, can you be more explicit about what API(s) you'd like disallowed?

**Comment by tsmethurst** [comment]
Ah, GoToSocial already does this by default :) You can't access any of the client APIs (except the /api/v1/instance endpoint) without being authorized.

**Comment by tsmethurst** [comment]
Oh okay I see what you're getting at. The difference there is that when you open a profile page in your browser, Mastodon serves a React web app that calls the backend API to get its data. When access to the backend is disallowed, you then get that cavalcade of 401 errors, and the app sort of breaks when you try to scroll down.

In GoToSocial's case, the web view of a profile is just an HTML web page that's templated by the backend; it doesn't make any API calls. So having some kind of `DISALLOW_UNAUTHENTICATED_API_ACCESS` option doesn't make any sense here, because it wouldn't change anything.

So -- correct me if I'm wrong -- I think what you're asking for here is some kind of setting that hides your profile page? Or just doesn't show any posts, even if you've made public posts? Is that right?

**Comment by tsmethurst** [comment]
Got ya :) If it's alright with you, I'll rename this issue to better reflect the feature request.
