### ISSUE TITLE
[feature] Timeline api for hashtag

### ISSUE THREAD

**Issue by leopku** [superseriousbusiness/gotosocial#327]
After clicking hashtag in status content, page jumped to https://pinafore.social/tags/tag1.

But there was an 404 error while requesting `/api/v1/timelines/tag/tag1?limit=20`.

Does there any plan for implementing timeline api for hashtag?

**Comment by tsmethurst** [comment]
Heya! Yep, we're planning to include it, but don't have a fixed idea of exactly when yet. Some time after the new year, probably :)

**Comment by leopku** [comment]
@tsmethurst Thanks.

Actually I tried to implement it. But I got a trouble while mounting routes `/api/v1/tag/{hashtag}`. Source code was [here](https://github.com/leopku/gotosocial/blob/9cfa0c62aed6f39c1bbd0b51d3098b7c82ef266f/internal/processing/timeline.go#L130).

Could you please give some advise to it?

Thanks a lot.

**Comment by tsmethurst** [comment]
I'm doing my day job rn but I'll try to find time tonight to have a look, and I'll get back to you :)

**Comment by leopku** [comment]
> I'm doing my day job rn but I'll try to find time tonight to have a look, and I'll get back to you :)

Appreciate it. @tsmethurst

**Comment by tsmethurst** [comment]
Heya, yeah i see an issue in the way your path is being set up when passed to gin. Right now you're using `/api/v1/timelines/tag` but what you need is `/api/v1/timelines/tag/:hashtag` or something similar. You might wanna check both the gin gonic documentation (https://github.com/gin-gonic/gin) and some of the other api handlers (like the accounts handler for instance: https://github.com/leopku/gotosocial/blob/9cfa0c62aed6f39c1bbd0b51d3098b7c82ef266f/internal/api/client/account/account.go ) to see how to work with keys in URL paths rather than keys from queries.

**Comment by leopku** [comment]
@tsmethurst Big thanks. 

I fixed it.

**Comment by tsmethurst** [comment]
Related: https://github.com/superseriousbusiness/gotosocial/issues/967
