### ISSUE TITLE
[bug] Federation errors on new instance behind Caddy

### ISSUE THREAD

**Issue by atalii** [superseriousbusiness/gotosocial#3390]
### Describe the bug with a clear and concise description of what the bug is.

I just set up an instance at https://fedi.tali.network/ to run behind Caddy. My config is done through NixOS and visible [here](https://github.com/atalii/net/blob/main/gardiner/configuration.nix). I seem to be unable to follow or be followed by any users (follow request are received, but I don't see if they're accepted). More reproducibly, whenever I post anything, I get this log line, leading me to think that something's wrong on gotosocial's end:

```
Oct 04 23:21:00 gardiner gotosocial[31763]: timestamp="04/10/2024 23:21:00.095" func=workers.(*clientAPI).CreateStatus level=ERROR msg="error federating status: CreateStatus: error sending Create activity via outbox http://fedi.tali.network/users/me/outbox:  http://fedi.tali.network/users/me/followers resp was not ActivityPub media type: "
```
I'm running this behind Caddy, which again is configured as shown in the linked nixOS module. My /etc/caddy/caddy_config` is:

```
{
	log {
		level ERROR
	}
}

fedi.tali.network {
	log {
		output file /var/log/caddy/access-fedi.tali.network.log
	}

	reverse_proxy * http://127.0.0.1:8080 {
		flush_interval -1
	}
}
```

Would you be able to let me know if this is a misconfiguration or a bug? Thanks!

### What's your GoToSocial Version?

0.16.0

### GoToSocial Arch

arm64 binary

### What happened?

I set up the server on NixOS running on a VPS and am unable to interact with other servers.

### What you expected to happen?

I should be able to interact with other servers.

### How to reproduce it?

Post something from my server (https://fedi.tali.network).

**Comment by firescry** [comment]
Hello, fellow GoToSocial-behind-Caddy user here 👋
I've noticed that part of resources on your instance are served over http, e.g. avatar picture on your profile but also federation endpoints presented to other instances - [https://webfinger.net/lookup/?resource=%40me%40fedi.tali.network](https://webfinger.net/lookup/?resource=%40me%40fedi.tali.network). URL in your error log also starts with http.
I think that communication over https is mandatory for federation to work properly. Is there any chance that your GoToSocial instance is configured to use http instead of https? Maybe this "protocol" parameter is a culprit - [config.yaml#L97](https://github.com/superseriousbusiness/gotosocial/blob/d3d6e3f920ee4b9c5909d0f03f9b21b953c3ce3c/example/config.yaml#L97)?

My instance works fine with Caddy and my Caddy setup for reverse-proxy is same as yours. The only difference that I spot is just this http vs. https protocol :thinking:

**Comment by tsmethurst** [comment]
Mmm indeed, that looks like you started up with `protocol=http`, then stopped, changed it to `protocol=https` and started it again, is that the case? When GtS first starts and you create a user and all that jazz, it generates URIs for the user based on protocol + host, so if you previously started with http and then changed to https, you'll have messed up those URIs.

**Comment by atalii** [comment]
Thank you both - that looks like it could explain a lot (and I was wondering about the profile picture thing, too!). Is there any way to change that after the fact, or should I just wipe state and try again?

Thanks again :)

**Comment by tsmethurst** [comment]
You should wipe state and try again, but you'll want to use a different username after the wipe, as remote instances you tried to federate with may have already stored your previous actor with the `http` protocol instead of the `https` one, and they'll just assume it's the same actor after the wipe and continue to not work. Something like `@me2` or `@tali` perhaps? :P

**Comment by atalii** [comment]
It looks like this is working - thanks so much for catching that!
