### ISSUE TITLE
storage-local-base-path: "/gotosocial/storage" cannot be overridden at ENV or FLAG level.

### ISSUE THREAD

**Issue by gedw99** [superseriousbusiness/gotosocial#3503]
The config file has "storage-local-base-path" value.

I could not see the ability to override this using ENV or FLAGS at deployment time.

I personal like to have control over storage paths at deployment time so you can more easily control the mapping of logical to physical storage.

**Comment by tsmethurst** [comment]
Hmm, it should work. Did you check out the documentation here? https://docs.gotosocial.org/en/latest/configuration/ Not every flag is listed in the "help" command because there's a colossal amount of them, but `storage-local-base-path` ought to work with the flag `--storage-local-base-path` or the env var `GTS_STORAGE_LOCAL_BASE_PATH`. Did you try those?
