### ISSUE TITLE
When I visit my domain. It shows 'ERR_TOO_MANY_REDIRECTS'.

### ISSUE THREAD

**Issue by SkysCrystal** [superseriousbusiness/gotosocial#358]
I've depolyed the program on Debian 11.  And followed the instruction in [Doc].(https://docs.gotosocial.org/en/latest/installation_guide/binary/).

After entering `./gotosocial --config-path ./config.yaml server start `,  it show:
```
time=2022-01-05T15:09:35+01:00 level=info msg=connected to SQLITE database
time=2022-01-05T15:09:35+01:00 level=info msg=there are no new migrations to run func=doMigration
time=2022-01-05T15:09:35+01:00 level=info msg=instance account goapub.cf already exists
time=2022-01-05T15:09:35+01:00 level=info msg=instance entry already exists
```

But when I visited the domain, it show `ERR_TOO_MANY_REDIRECTS` on my browser. Please help me fixing this problem. Thanks!

**Comment by ForestJohnson** [comment]
This error happens when a web application gets stuck in a redirect loop; it redirects to a page that redirects to a page that ... often when a page redirects to itself, or back and forth. 

It seems unlikely to me that gotosocial would do this by itself -- people run gotosocial all the time, and this is the first time I've heard of this happening.  So to me, that means this issue must be related to  something else in the environment where you are running it, for example, something unique in your config file, or perhaps a reverse proxy server in front of your gotosocial instance.

I know that  gotosocial has its own Let's Encrypt or "ACME" (Automated Certificate Management Environment) based  https support, which features a redirect from http to https.  Could it be that this redirect is accidentally being triggered even when you are technically visiting your site over HTTPS?  Otherwise, the only thing I can think of would be a redirect related to login, that your browser is infinitely being re-directed to a login page or something. 

In order to figure this out, there are two types of additional information you can provide: 

#### 1. Records of the redirects themselves

  - These can be accessed by opening the developer tools of your web browser and clicking on the "Network" tab.
  - The key command to open the developer tools is different depending on your web browser / operating system. See [Finding Your Browser's Developer Console](https://balsamiq.com/support/faqs/browserconsole/#apple-safari)
  - Each request is a line item in the list, and you can "drill down" into the request and response details by clicking on it. We are probably interested in the request method (GET or POST) the request path ( probably `/` ) and the `Location` header on the HTTP response, which tells the browser where to redirect to. 
    
Here's an example from my gotosocial instance: 
![image](https://user-images.githubusercontent.com/7119703/148357830-af79e756-db21-4dd9-95cc-0781db468736.png)

Here's an example of a normal, healthy re-direct HTTP response; I intentionally edited the URL in the URL bar from `https://gotosocial.sequentialread.com/` to `http://gotosocial.sequentialread.com/` (`http://` vs `https://`), and it redirected me back to the secure protocol url: 

![image](https://user-images.githubusercontent.com/7119703/148358843-a05dc0ce-3ec8-499f-b005-cd5a2e1dec2f.png)


#### 2. Information about your environment

What is in your configuration file? Are you using a reverse-proxy server (Apache, nginx, Caddy) or any kind of web hosting service in conjunction with GotoSocial?  How does the connection get from your web browser to your gotosocial instance?

Also, if you are comfortable sharing, it might be easiest if you would share the domain name you are using so we can look at it ourselves.

**Comment by SkysCrystal** [comment]
@ForestJohnson Thanks for your detailed instruction! My domain is [Go a Pub](goapub.cf). And the server is an ipv6 only.

For part 1: 

![image](https://user-images.githubusercontent.com/49473463/148362562-0aaee783-0e15-4110-9e80-97543e599ba5.png)

And for part 2: It's just a new server. I checked that no Apache or nginx servies were used. And I'm using Cloudflare to make the domain connected to the server.

**Comment by SkysCrystal** [comment]
After I changed SSL/TLS to Strict in Cloudflare and added `https://` before the domain. Gotosocial service can be visited.

Though I don't know the reason, the problem seems to be solved.

@ForestJohnson Thanks a lot!
