### ISSUE TITLE
[feature] GtS CLI: block/unblock/etc… remote users and instances

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial#390]
## problem

currently there's no *CLI* to block/unblock/etc… remote users and instances

## work around

fiddle around in the database?
Setup the gotosocial-admin web interface?
and then secure it??

## proposed solution

with https://github.com/superseriousbusiness/gotosocial/issues/389 in place, we know who we are dealing with currently. We can go from there and block or pre-emptively allow instances.

When dealing with instances, especially, it would be good to be able to block access based on DNS patterns and IP-ranges.

Also, based on our knowledge from https://github.com/superseriousbusiness/gotosocial/issues/387 we may allow admins to re-federate with remote instances should they have lost their key. (That is: We'd delete the remote instances locally-cached key)

**Comment by tsmethurst** [comment]
I don't think this is something we'll do, now, since the functionality is now pretty extensively covered by the bundled admin panel and import/export of domain blocks and domain allows. Since blocking/allowing a domain requires access to a running database and state struct, it's not something we could easily do with the CLI anyway, since a separate CLI instance has no access to the internal state of a running GtS instance.

**Comment by igalic** [comment]
one way to do this kind of thing would be if the CLI would access the same API as the admin Web interface, but pre-authenticated, with an API token.

but at that point we'd just be duplicating the functionality of the admin Web interface for CLI snobs.

Otoh, it could be used for scripting /automation…
