### ISSUE TITLE
Confusing CLI flag parsing

### ISSUE THREAD

**Issue by f0x52** [superseriousbusiness/gotosocial#42]
apparently the correct format is something like `./gotosocial --host test server start`
but when doing the imo more logical `./gotosocial server start --host test` you just get a very vague flag parsing error :(

**Comment by tsmethurst** [comment]
It's to do with the way urfave (the cli library) differentiates between global parameters (that apply to all commands) and command-specific parameters.

Most of the config params are global parameters because they apply to multiple commands, so `--host` for example is needed not just for starting the server, but also for stuff like adding new users (because the command needs to know what hostname to use when generating new user URIs) and that sort of thing. Makes sense to use global params where possible to avoid code repeition, and those global params go immediately after the name of the executable.

I agree that it's confusing syntax though, and probably some (most?) of the global params could be moved to command-specific parameters.

There might also just be a better way in the library of doing it that I haven't looked into yet. I just chose this one because I've used it before in professional projects and know it works fine and is easy to implement, but I haven't properly looked into all the quirks of it yet.
