### ISSUE TITLE
[bug] Mastonaut App fails to look up instance and log in 

### ISSUE THREAD

**Issue by f2k1de** [superseriousbusiness/gotosocial#489]
My favorite Client-App [Mastonaut](https://mastonaut.app/) doesn't work with gotosocial. 

When i try to add an instance it doesn't allow me to do it:
![Bildschirmfoto 2022-04-25 um 19 04 59](https://user-images.githubusercontent.com/11199213/165142072-79dd4e1f-4c4d-45ab-b33e-3b0548020bc4.png)

I found out that it fails because the `thumbnail` key in the `/api/v1/instance` endpoint is empty. If i change that to something (it doesn't even have to be a working image, lol)... It can look the instance up:
![Bildschirmfoto 2022-04-25 um 19 04 12](https://user-images.githubusercontent.com/11199213/165142652-c6d84ee6-4b4c-4fce-b9b0-033f40e312cb.png)

If I try to connect the usual oauth-flow starts and it opens a browser with the gts login form, when i log in there i get:
![Bildschirmfoto 2022-04-25 um 19 08 26](https://user-images.githubusercontent.com/11199213/165143125-57c65bf7-484e-4285-8364-6f3c0fab036a.png)

If i click the Allow button it brings me back to the Mastonaut-App and gives me the following error:
![Bildschirmfoto 2022-04-25 um 19 38 21](https://user-images.githubusercontent.com/11199213/165143634-97587074-7c21-4856-93b5-7d2ff9783876.png)

Here is a capture of the auth-request:
![Bildschirmfoto 2022-04-25 um 19 09 34](https://user-images.githubusercontent.com/11199213/165144406-c0f129a9-2f47-4f8c-9e8a-673ff48b9955.png)

**Comment by tsmethurst** [comment]
Heya, just a little update on this:

I just spent like a day setting up a MacOS installation in qemu to try to replicate the bug. Got the virtual machine working, but then I get errors trying to download Mastonaut from the app store (even after giving it my phone number and an email address :grimacing: ). So unless someone gives me a Macbook or something, I won't be able to test fixes for this one. HOWEVER, I will take a look at the GtS code and the Mastonaut code (which is now open source apparently, as of 25 days ago) and try to figure out a solution.

**Comment by tsmethurst** [comment]
Oh, I think I see what's happening... It looks like Mastonaut submits scope as an array, whereas the Mastodon API expects scope to be a space-separated string. I'm surprised this works with Mastodon, perhaps they're more lenient than we are :thinking: I'll try and implement a fix for this...

**Comment by tsmethurst** [comment]
Heya, I came up with a workaround for this, but after some discussion with the other devs we decided not to merge it into main. The reason being is that what we're doing is oauth spec compliant, and also mastodon-api compliant, so really it should be an issue that the Mastonaut developers should fix (or whoever ends up forking Mastonaut, since it's now unmaintained).

Also, it's unclear to us why this works on other Mastodon instances, when they also specify that scopes should be a space-separated string :thinking: 

In any case, if you'd like to implement the fix just for your own instance of GtS, you can use the above closed/unmerged PR as a guide for doing so.

I will close this issue now because it's not something we will fix, but if you'd like to discuss it etc feel free to reply :)
