### ISSUE TITLE
Co-op Cloud deployment questions: reverse proxy & CLI flags / env vars

### ISSUE THREAD

**Issue by decentral1se** [superseriousbusiness/gotosocial#62]
Thanks for all this wonderful work!

I'm looking into packaging `gotosocial` for https://coopcloud.tech for early testing and as we use https://doc.traefik.io/traefik/ as our default automagic "take care of TLS for me" reverse proxy, I am wondering how that interacts with the built-in (!) automagic TLS handling in `gotosocial`. Can `gotosocial` be run in the usual HTTP mode? Do I just set `--letsencrypt-enabled=false`? 

Also, I'm wondering what is the default minimal configuration I need to run the binary? When I run it just plain `server start`, I see `FATA[0000] error parsing config: host was not set` and I am wondering are there docs to help with knowing what is mandatory and what isn't?

Finally, is it possible to pass command line flags as environment variables? That woule be handy.

I can help write docs if you point me in the right direction :rocket:

**Comment by tsmethurst** [comment]
Heya! Thanks!

I also use Traefik for lots of things so it was important to me that GtS is decently compatible with it.

You can indeed just run GtS in normal http mode without letsencrypt by setting the flag to false, or indeed just not setting it all, since the default is false :) Then GtS will run on port 8080 and you can point Traefik towards that port -- in the future the ports will be configurable, see https://github.com/superseriousbusiness/gotosocial/issues/43.

The default minimal configuration is just setting the --host flag, that's the only one you still need to set manually and the rest have defaults. If you run `gotosocial --help` you should see a list of all the flags that you can set, alongside their defaults. So for an extremely basic server config, you can run `gotosocial --host example.org server start`

You can indeed pass arguments as environment variables! They're listed in the --help command as well :) You can also use a yaml configuration file, but this isn't documented yet.

If you're testing deployment and you wanna write some docs as you go along (sort of a 'how to get started' thing) that would be really appreciated! I didn't get around to writing that document myself yet, so help would be very very welcome <3

**Comment by decentral1se** [comment]
I'm gonna follow https://github.com/superseriousbusiness/gotosocial#getting-started now :rocket: 

Will close this off once I have an instance up :hugs:

**Comment by decentral1se** [comment]
https://gts.autonomic.zone :metal:
