### ISSUE TITLE
[bug] Release artefact doesn't contain built assets

### ISSUE THREAD

**Issue by igalic** [superseriousbusiness/gotosocial#654]
### Describe the bug with a clear and concise description of what the bug is.

When downloading the supposed release tarball (not the source!) from https://github.com/superseriousbusiness/gotosocial/releases/tag/v0.3.5, I'm faced with two issues:

1. it's a [tar bomb](http://www.linfo.org/tarbomb.html)
2. it doesn't contain the built CSS assets, so deploying it leads to lots of 404s

### What's your GoToSocial Version?

v0.3.5

### GoToSocial Arch

nah.

### What happened?

I tried to update the [gotosocial packaging for FreeBSD](https://github.com/freebsd/freebsd-ports/tree/main/net-im/gotosocial)
I switched the built from using the raw tag, to using the released tar ball: https://github.com/superseriousbusiness/gotosocial/releases/download/v0.3.5/gotosocial-0.3.5.tar.gz

That thing does not contain the web/assets/dist

### What you expected to happen?

I expected it to contain web/assets/dist

(i also expected it to not explode all over my filesystem when untaring it)

### How to reproduce it?

Download https://github.com/superseriousbusiness/gotosocial/releases/download/v0.3.5/gotosocial-0.3.5.tar.gz
untar it (into a subdirectory)

look into web/assets/dist
it's not there.

### Anything else we need to know?

Please don't make me use node and npm or yarn in a build system.

And please don't tell me to just use the readily built release for FreeBSD.
The point of having native packages is that they are built within the parameters the build chain or the user supplies.

(and we have some ways to go there, like, for instance right now there's no way to build WITH_DEBUG rn, that is: Have debug symbols preserved, without hackery that i didn't want to expend too much energy on.)

**Comment by f0x52** [comment]
i did not know this either at first, but [gotosocial-0.3.5.tar.gz](https://github.com/superseriousbusiness/gotosocial/releases/download/v0.3.5/gotosocial-0.3.5.tar.gz) is a tar of the entire repo at time of release (so no builds), for bundled assets you need to download one of the platform specific tars, like [gotosocial_0.3.5_freebsd_amd64.tar.gz](https://github.com/superseriousbusiness/gotosocial/releases/download/v0.3.5/gotosocial_0.3.5_freebsd_amd64.tar.gz)

as for the "tar bomb", goreleaser has an option to wrap everything in a directory, we'll look into that. But in general i guess the recommendation is to always list a tar's contents before extracting it, you can't expect every downloaded tar to be proper?

**Comment by tsmethurst** [comment]
I think in future we will just remove that particular tar from the goreleaser, because it's confusing and doesn't add anything (iirc) that's not already include in the platform release tars. It's basically just an artefact thrown in by GoReleaser, which we can toggle off.

Either that or, since the compiled javascript and css files in web/assets/dist are platform agnostic, we can update the tar mentioned above to *only* include those assets, although that's also a bit weird.

Third option, we commit the compiled js/css to the repo. That also seems not quite right to me, but for the sake of convenience it might be the way to go..

**Comment by igalic** [comment]
*\*puts on dusty C developer and release manager hat\**

in the C world, in autotools based projects, the `configure` file is never committed, it can be easily (re)generated, and frequently might need to be during a development cycle.

but it's part of a release tar ball

in my view, the dist files are a similar case.
this is a ***backend*** focused ***go*** project first and foremost. if it was a node project i wouldn't be complaining about these files missing. but then i probably wouldn't attempt to package it for FreeBSD, and instead suffer in silence.

one option you can go with is to create a release branch, build and commit the dist files there, and tag from this branch. this is fiddly, because if gitignore, so it should be automated.

*\*throws dusty C developer and release manager hat\ into the flames**

**Comment by tsmethurst** [comment]
@igalic I marked this as closed by the above PR because it solves the main problem of the web assets not being available separately in a tar. It also mitigates the tarbomb issue by removing the offending source tar that contained lots and lots of files, but if you wanna reopen this or make another issue about the tarbomb thing we can still discuss it :) hope that's OK with you
