### ISSUE TITLE
Consider _FILE convention for secrets in deployment

### ISSUE THREAD

**Issue by decentral1se** [superseriousbusiness/gotosocial#66]
`GTS_DB_PASSWORD` could be read from a file then by passing `GTS_DB_PASSWORD_FILE`.

This is something https://hub.docker.com/_/postgres supports for example:

![image](https://user-images.githubusercontent.com/1991377/123522176-05891e00-d6bc-11eb-8350-2ee5ea352f77.png)

This makes it possible to avoid having to work around the fact that Docker swarm does not make it possible to pass secrets in via the environment with a custom entrypoint hack like in https://git.autonomic.zone/coop-cloud/gotosocial/src/commit/62ecb0fd879c8ac0145d87414e24cbd9435fd305/entrypoint.sh#L23.

**Comment by tsmethurst** [comment]
Yep! Good one, shouldn't be too hard to add, I'll look into it :+1:

**Comment by tsmethurst** [comment]
I'm considering closing this one because the functionality is now handled pretty well by just putting secret variables in the config.yaml file (https://github.com/superseriousbusiness/gotosocial/blob/main/example/config.yaml). You could, for instance, just put your sensitive things in that file, and then pass the rest of your non-sensitive variables via env vars :thinking: What do you think?

**Comment by decentral1se** [comment]
Perfect, thank you! I will catch up with the Co-op Cloud packaging soon and use this `config.yaml` :partying_face:
