### ISSUE TITLE
[feature] Ask for the support of the common `password grant flow`

### ISSUE THREAD

**Issue by jianguda** [superseriousbusiness/gotosocial#677]
### Is your feature request related to a problem ?

I am developing a frontend application using gotosocial as the backend server. However, it is not very satisfying that gotosocial only supports `authorization code flow` and `client credentials flow`.

### Describe the solution you'd like.

It seems not that convenient to rely on the `authorization code flow` in some cases, is it possible to support the common `password grant flow` as well?

### Describe alternatives you've considered.

no alternatives.

**Comment by tsmethurst** [comment]
Heya! Thanks for opening this. I'll discuss it with the other devs and see if we can reach a consensus on it. My preference would be to not implement it because it feels less secure, but that's just a knee-jerk response and I need to do some proper research into it :P

**Comment by jianguda** [comment]
Thanks! Actually, the scenario is building bots for pushing news or updates, and we feel it seems natural to get access code through `password grant flow`. (We are trying to migrate from Mastodon but just realized that it is not yet supported here.)

**Comment by tsmethurst** [comment]
Heya! Firstly I think Mastodon actually does implement this, if i remember rightly, it's just not documented :thinking:  I *think*.

Also, I did some research and spoke to the other devs about this and we decided it's not something we're going to support, since the `password` grant type is going to be deprecated soon in the official oauth spec, and it's already recommended that it not be used (see https://oauth.net/2/grant-types/password/).
