### ISSUE TITLE
[bug] Fetching home timeline with limit of 1 sometimes returns empty response

### ISSUE THREAD

**Issue by fruitsbat** [superseriousbusiness/gotosocial#748]
### Describe the bug with a clear and concise description of what the bug is.

When fetching the home timeline with limit 1 sometimes an empty response with status code 200 gets returned.

https://kittycat.homes/api/v1/timelines/home?limit=1&max_id=01GA3RT1YR04AKFCEZ14KKYKV8

### What's your GoToSocial Version?

0.3.8

### GoToSocial Arch

arm64 binary

### What happened?

got an empty response body from the server, the headers are also missing link attribute

### What you expected to happen?

either a different status code or a regular response body

### How to reproduce it?

https://kittycat.homes/api/v1/timelines/home?limit=1&max_id=$ID a lot of times for different ids

**Comment by tsmethurst** [comment]
I think this has been resolved now with the way that we create Link response headers. If you now request a limit of 1, and it happens to include a post that gets filtered out before the client gets it, the Link headers will still be set properly so that the client can page past that post by doing another request.
