### ISSUE TITLE
[feature] Refresh account profile fields + avi + header when webfingering

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#822]
Sometimes account updates from remote instances get lost in the ether! And we end up showing outdated profile pics and headers and bios on accounts.

We already have a mechanism for doing a sort-of-refresh on remote accounts every 48 hours by webfingering them again (https://github.com/superseriousbusiness/gotosocial/blob/main/internal/federation/dereferencing/account.go#L200-L210).

We could expand this logic to also refresh account bio and images and stuff. This should mean that at most, an account seen by a user on GtS will be out of date by 2 days, which is sorta OK!

**Comment by trysdyn** [comment]
+1 for the reason that since #1234, we can throw out account avatars/headers and re-fetch attempts later will go to old cached URLs and fail. If I'm not following a user (for example: someone who frequently gets boosted into my TL), their bio/avatar/header never updates in my DB after first dereference.

**Comment by tsmethurst** [comment]
closed by https://github.com/superseriousbusiness/gotosocial/pull/1411
