### ISSUE TITLE
[feature] Allow users to opt in to showing their Unlisted posts via the web

### ISSUE THREAD

**Issue by tsmethurst** [superseriousbusiness/gotosocial#900]
Right now we only ever show Public statuses on the web ui (whether on the account's profile, or via a status link).

This behavior can be a bit confusing for users coming over from Mastodon, which shows both Public and Unlisted posts via the web. Oftentimes, users expect to be able to open Unlisted links in their browser and see the status, whereas now the page returns a 404 and an explanatory message.

To alleviate this, it might be nice to create a setting so that users can choose to have their Unlisted posts rendered via status links, as though they were Public posts. This should be off by default to keep the existing behavior.

**Comment by NyaaaWhatsUpDoc** [comment]
So would the usage here be that unlisted posts don't show on the profile, but if they opt-in via account setting then the individual URL by status ID would work?

I have definitely fallen into this trap of attempting to share a status only to remember it won't be visible 😅

**Comment by daenney** [comment]
There's a pattern of usage where someone starts with a public post, but then makes the follow-up posts unlisted. This is a nice way of doing threads without overloading the public timeline. Folks can see the opening post and follow along, but if they're not interested the rest doesn't show up in their home timeline.

For that pattern, it would be nice if we showed unlisted replies by the original author (that are chained to the opening post) in our web view too. That lets you view the complete thread, as it were. It might be nice to have a separate user preference for that behaviour though and not roll that into the same setting.

Personally I use unlisted because for a bunch of things I don't want them to be that level of public by default. But in this particular case I'd like the whole thread to be viewable as the reason I'm using unlisted is to not overwhelm other's timelines, not to limit hot-linking.
