### ISSUE TITLE
[feature] Allowlist mode for federation

### ISSUE THREAD

**Issue by blipdrifter** [superseriousbusiness/gotosocial#963]
### Is your feature request related to a problem ?

I would much prefer to run an instance where the federated instance list is based upon a list of instances I approve of, instead of having to block a zillion garbage instances whenever I set up my own instance with GTS. There are a few Mastodon instances that have this feature added already (most notably awoo.space), so it's definitely doable.

### Describe the solution you'd like.

Add a whitelist mode to the config settings of GTS, as well as a place to put the instances I want to federate with.

### Describe alternatives you've considered.

NONE

**Comment by tsmethurst** [comment]
i edited some of the wording in the issue a bit to reflect the terminology we're gonna use: allowlist + blocklist -- hope that's ok :)

**Comment by Shadow8t4** [comment]
Seconding this - honestly, as someone who has run a fediverse instance on their own for years since the start basically, it's _a lot more work_ trying to maintain a blocklist of instances rather than simply listing the ones that are allowed to federate. It's honestly the feature that's keeping me from migrating my own instance to GoToSocial full-time. If GoToSocial's main goal is to be geared towards primarily single-user and small instances, this would help a lot. There are plenty of folks out there that run single-user instances and small instances out of wanting privacy and control.

For reference to what Mastodon's implementation does, setting allowlist mode blocks anyone who isn't signed in from seeing posts, even public ones and profiles, and removes public access to most API calls. I'm not sure if I'd say _all of those things should be necessary and default_ along with this setting, but it's something else to consider.
