### ISSUE TITLE
[feature] Faster docker getting started for single user installs

### ISSUE THREAD

**Issue by manfre** [superseriousbusiness/gotosocial#978]
### Is your feature request related to a problem ?

The existing docker instructions require many manual steps on both the host instance (creating folders) and the gts container (creating/promoting the admin user). For a single user instance, the getting started process could be simplified to allow launching the container using existing container web UI tools (qnap container station, portainer, etc.)

### Describe the solution you'd like.

I'd like to be able to paste a docker compose file in to portainer UI, set an envFile and have it start the instance without other manual intervention.

### Describe alternatives you've considered.

none

**Comment by manfre** [comment]
I've created a PR that creates necessary folders on the container and provides an alternative entry point sh script.
https://github.com/superseriousbusiness/gotosocial/pull/977

**Comment by manfre** [comment]
PR feedback raised concerns about adding complexity. 

For this feature, the following questions need to be answered:

* Does gts want to provide the ability to define an admin user from configuration values?
  * Should this user be an "only if not exists" bootstrap operation?
  * Should this user have its email and password updated on each launch to match the configuration?

**Comment by tsmethurst** [comment]
I'm going to close this since I don't think it's really necessary, we provide clear instructions for creating the first admin user (and other users) in the documentation. I don't think it provides much additional benefit to write code for creating the first admin user (and therefore keeping that user's credentials around in config) when it's just one extra CLI command.
